(function(g){var window=this;var jZ=function(a){a.i||(a.i=new g.Ao,g.G(a,a.i));return a.i},kZ=function(a,b,c){var d=g.V(a.app);
b.event="iv";a.isFullscreen()&&(b.fs=1);b.ux=1;d.logEvent(b,c)},lZ=function(a){a.M("cardstatechange",a.ud()&&a.Ce()?1:0)},mZ=function(a){var b=g.Lh(a);
a=g.Sh(a);return new g.nh(b.x,b.y,a.width,a.height)},nZ=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},oZ=function(a){return"none"!=a.style.display},pZ=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);
var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e},Mna=function(a){var b=g.Fh(a,"fontSize");
var c=(c=b.match(Jna))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Md){if(String(c)in Kna)return pZ(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Lna)return a=a.parentNode,c=g.Fh(a,"fontSize"),pZ(a,b==c?"1em":b)}c=g.Rd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Xd(c);return b},Nna=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Ck&&a.dataset){if(g.kc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.fd("pollChoiceIndex"))},sZ=function(a){a=g.Ra(a);
delete qZ[a];g.Yb(qZ)&&rZ&&rZ.stop()},tZ=function(){rZ||(rZ=new g.M(function(){Ona()},20));
var a=rZ;a.isActive()||a.start()},Ona=function(){var a=(0,g.H)();
g.Lb(qZ,function(b){uZ(b,a)});
g.Yb(qZ)||tZ()},vZ=function(a,b){g.sf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},wZ=function(a,b,c,d){g.Vn.call(this);
if(!g.Ma(a)||!g.Ma(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.A=null},uZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;xZ(a,a.progress);1==a.progress?(a.g=0,sZ(a),a.Xc(),a.l()):1==a.g&&a.Lr()},xZ=function(a,b){g.Oa(a.C)&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},yZ=function(a,b,c,d,e){wZ.call(this,b,c,d,e);
this.element=a},zZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
yZ.call(this,a,b,c,d,e)},Pna=function(a){return Math.pow(a,3)},Qna=function(a){return 3*a*a-2*a*a*a},AZ=function(a){g.D.call(this);
this.i=a||window;this.g=[]},Rna=function(a,b,c,d){c=(0,g.x)(c,d||a.i);
b=g.Vr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},BZ=function(a,b){(0,g.A)(b,function(c){g.ds("visualElementShown",{csn:a,
ve:g.Ks(c),eventType:4},g.is,void 0,void 0)})},CZ=function(a,b){(0,g.A)(b,function(c){g.ds("visualElementHidden",{csn:a,
ve:g.Ks(c),eventType:8},g.is,void 0,void 0)})},DZ=function(a,b){g.Sf.call(this);
this.Sj=a;this.Yp=b;this[g.uf]=!1},IZ=function(a,b,c,d){DZ.call(this,a,b);
a=this.Yp;b=this.ga();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.Fa(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Sna(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Yp;a=this.ga();if(d instanceof EZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof FZ){b="lg-"+d.u+"-"+d.C+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=GZ(c,"linearGradient",{x1:d.u,y1:d.C,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ha(d.l)&&(f+=";stop-opacity:"+d.l);f=GZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ha(d.o)&&(f+=";stop-opacity:"+d.o);d=GZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=HZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},JZ=function(){},KZ=function(a,b){DZ.call(this,a,b)},LZ=function(){this.Ta=[];
this.Ca=[];this.Sd=[]},MZ=function(a,b,c,d){var e=a.xd[0]-b*Math.cos(g.td(d))+b*Math.cos(g.td(d+90)),f=a.xd[1]-c*Math.sin(g.td(d))+c*Math.sin(g.td(d+90));
a.Ta.push(3);a.Ca.push(1);a.Sd.push(b,c,d,90,e,f);a.Wk=!1;a.xd=[e,f]},Una=function(a,b){for(var c=a.Sd,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=Tna[k]*a.Ca[e];
b(k,c.slice(d,d+l));d+=l}},NZ=function(a,b,c,d){IZ.call(this,a,b,c,d)},h_=function(a,b){this.g=a;
this.i=b},v_=function(a,b,c,d,e){g.go.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},Sna=function(a){var b=a.Hj();
return b?b.width/(a.l?new g.wd(a.l,a.I):a.Hj()).width:0},FZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.C=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ea(k)?k:null;this.o=g.Ea(l)?l:null},EZ=function(a,b){this.F=a;
this.H=null==b?1:b},w_=function(a,b){DZ.call(this,a,b)},x_=function(a,b,c,d){IZ.call(this,a,b,c,d)},y_=function(a,b,c,d,e){v_.call(this,a,b,c,d,e);
this.g={};this.R=g.Od&&!g.od(526);this.P=new g.$m(this)},GZ=function(a,b,c){a=a.N.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},z_=function(a,b,c,d){b=GZ(a,"path",{d:Vna(b)});
c=new x_(b,a,c,d);a.o.ga().appendChild(c.ga())},Vna=function(a){var b=[];
Una(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},HZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+Wna++;c.setAttribute("id",d);a.g[b]=d;a.C.appendChild(c);return d},Xna=function(){A_||(A_=new g.Fg(400),A_.start());
return A_},B_=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.B)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.B)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.Js(a.trackingParams));var k=(0,g.B)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.jv=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.B)(u.loggingUrls||[],c);p.Cl=g.Tb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.B)(n.impressionUrls||[],c);p.ND=(0,g.B)(n.hovercardShowUrls||[],c);p.Wb={itct:n.trackingParams};p.visualElement=g.Js(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Bm=!1,p.Zn=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Bm=!1,p.Zn=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Tb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.Bm=!1;p.Zn="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var z=d(r.subscribedButtonText);if(r.subscribed){var C=d(r.subscriberCountWithUnsubscribeText);var E=d(r.subscriberCountText)}else C=d(r.subscriberCountText),
E=d(r.subscriberCountWithSubscribeText);var F=null;if(n.signinEndpoint&&(F=g.Tb(n,"signinEndpoint","webNavigationEndpointData","url"),!F)){n=void 0;break a}if(u&&(z||F)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:C,unsubscribeText:z,unsubscribeCount:E,enabled:r.enabled,signinUrl:F,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Tb(u,"urlEndpoint","url"),p.Bm=!0,p.Zn="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.Yd)(k,function(l){return!!l});
return f},C_=function(a){g.rK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.C={};this.A=this.l=null;this.I=[];a=g.X(a);this.P=g.Dy(a)||g.Fy(a);this.yA=!0;this.D=0;this.F=new g.Ln;this.u=new g.us(this);g.G(this,this.u);this.u.K(this.player,g.SD("creatorendscreen"),this.IE);this.u.K(this.player,"crx_creatorendscreen",this.JE);this.u.K(this.player,"resize",this.ib);this.u.K(window,"focus",this.AL);this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},D_=function(a){return a.player.getVideoData().Mb?"current":a.P?"new":"current"},E_=function(a){return"creator-endscreen-editor"===a},F_=function(a,b){g.$J(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.C={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){Yna(a);c=[];var d=new g.PD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.X(a.player).g||(a.l=new g.W({B:"div",G:"ytp-ce-shadow"}),g.dK(a.player,a.l.element,4),a.A=new g.OP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Zna(a,e);a.g[e.id]=f;a.C[e.id]=e;g.dK(a.player,f.element,4);var k=new g.PD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);$na(a,f,e)}g.XJ(a.player,
c);a.ib()}},Yna=function(a){var b=g.Zs(),c=g.$s();
c&&b&&a.i.visualElement&&g.Ls(c,b,[a.i.visualElement],void 0)},Zna=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={B:"div",V:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.Cl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:G_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:H_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",V:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Mn(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={B:"div",V:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.Cl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:G_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:H_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",V:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Mn(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-playlist-count",J:[{B:"div",
G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={B:"div",V:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.Cl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body",J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"a",V:["ytp-ce-channel-title","ytp-ce-link"],L:{href:H_(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Mn(a.F,b.title||"")},U:b.title},b.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",J:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{B:"div",V:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],U:b.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:G_(b)}]};c=new g.W(c);var d=g.Fd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.X(a.player).g){var e=null;var f=b.Wb.itct}else e="endscreen",f=null;e=new g.FV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={B:"div",V:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.Cl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",J:[{B:"div",G:"ytp-ce-expanding-overlay-body",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"div",G:"ytp-ce-website-title",L:{dir:g.Mn(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-website-metadata",U:b.metadata},{B:"a",V:["ytp-ce-website-goto","ytp-ce-link"],L:{href:H_(a,b.targetUrl),target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:G_(b)},{B:"div",G:"ytp-ce-expanding-icon",L:I_(b.iconUrl)}]},c=new g.W(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},G_=function(a){if(a.jv)var b=
a.jv.thumbnails;
return I_(b?b[b.length-1].url:null)},I_=function(a){return a?{style:"background-image: url("+a+")"}:{}},$na=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.x)(a.Zq,a,b,c));b.ca("mouseleave",(0,g.x)(a.Qr,a,b,c));g.X(a.player).g||b.ca("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.x)(a.Fy,a,c));b.ca("keypress",(0,g.x)(a.Fy,a,c));b.ca("focus",(0,g.x)(function(l,m){this.Zq(l,m)},a,b,c));
b.ca("blur",(0,g.x)(function(l,m){this.Qr(l,m)},a,b,c));
b.ca("touchstart",(0,g.x)(a.Zq,a,b,c));var f=g.Hd("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Sn(b.element,"ytp-ce-element-hover");g.Sn(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.x)(function(l,m){this.yA=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.D+=n;0<this.D?(g.J(l.element,"ytp-ce-force-expand"),J_(this,m.id,!0)):(g.Sn(l.element,"ytp-ce-force-expand"),g.Sn(l.element,"ytp-ce-element-hover"),J_(this,m.id,!1))},a,b,c);
a=(0,g.x)(function(l,m){m&&(l.ca("blur",function(){oZ(m)&&this.yA&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Hd("ytp-sb-subscribe",b.element));a(g.Hd("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},H_=function(a,b){var c=g.X(a.player);
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.iz(c)+b}else return"";return b},J_=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},K_=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||E_(g.X(a.player).playerStyle))c&&c();else{b=aoa(a,b);var e=0,f=!1,k=new g.M(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Zq(b[a],d)}},L_=function(a,b,c){K_(a,b.clickUrls,c);
(a=g.$s())&&b.Bm&&g.Ns(a,b.visualElement)},aoa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(boa(b[e],c));return d},boa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},M_=function(a){return g.Ma(a)&&a.length?a[0]:a},N_=function(a){var b=/.+/;
return g.Fa(a)&&null!=b&&null!=a&&a.match(b)?a:""},O_=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},P_=function(a){return g.Fa(a)?a:""},Q_=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},R_=function(a,b){return"true"==a||"false"==a?"true"==a:b},S_=function(a,b){return g.Fa(a)?parseFloat(a):b},T_=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.qd(a,b,c);if(a>=b&&a<=c)return a}return e},coa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.A)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},U_=function(a,b){if(null==a)return null;
if(g.Na(a)){var c=[];(0,g.A)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},doa=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.kh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},eoa=function(a){function b(c){return(0,g.Yd)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},foa=function(a){this.externalId=a},goa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},V_=function(a){if(!a)return null;
var b=g.Dc(P_(a.value));b=g.Ac(b);if(!b)return null;var c=Q_(a.target,hoa,"current");return null==c?null:new goa(b,c,R_(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},W_=function(a){return a.value?a.value:null},ioa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},loa=function(a){if(!a)return null;
var b=Q_(a.type,joa),c=Q_(a.trigger,koa),d=M_(a.url);d=V_(d?d:null);a=M_(a.subscribeData);var e=a?a:null;e?(a=P_(e.external_user_id),e=P_(e.subscription_token),a=a&&e?new foa(a):null):a=null;return b?new ioa(b,c,d,a):null},X_=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},Y_=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},Z_=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Wi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.C=l;this.o=m;this.i=n;this.g=p},$_=function(a,b){if(!a)return null;
var c=S_(a.x,0),d=S_(a.y,0),e=S_(a.w,0),f=S_(a.h,0),k=coa(a.t),l=S_(a.d,0),m=S_(a.px,0),n=S_(a.py,0),p=S_(a.scaleSlope,1),r=S_(a.scaleSlopeX,p);p=S_(a.scaleSlopeY,p);var u=Q_(a.scaleDimension,moa,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},c0=function(a,b){var c=a0(b,b0(a,new g.nh(a.x,a.y,a.Wi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.qd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.qd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},b0=function(a,b,c){var d=a.A,e=a.C,f=a.g?a.g:"xy",k=X_(c,a.o,f);
a=Y_(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.nh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},d0=function(a){return a?$_(a,function(b,c,d,e,f,k,l,m,n,p,r){return new Z_(b,c,d,e,f,k,l,m,n,p,r)}):null},e0=function(a,b){this.g=a;
this.i=b||null},a0=function(a,b){var c=a.i?c0(a.i,new e0(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.ud?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ha(c)&&(d.top+=c));return d},f0=function(a,b,c,d,e,f,k,l,m,n,p,r,u){Z_.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},noa=function(a){if(!a)return null;
var b=S_(a.sx,0),c=S_(a.sy,0);return $_(a,function(d,e,f,k,l,m,n,p,r,u,z){return new f0(d,e,f,k,l,b,c,m,n,p,r,u,z)})},ooa=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=z},g0=function(a){if(!a)return null;
var b=O_(a.fgColor,"#1A1A1A"),c=O_(a.bgColor,"#FFF"),d=O_(a.borderColor,"#000"),e=T_(a.borderWidth,0,5,!1,0),f=T_(a.bgAlpha,0,1,!1,.8),k=O_(a.highlightFontColor,"#F2F2F2"),l=T_(a.highlightWidth,0,5,!1,3),m=P_(a.textAlign),n=T_(a.textSize,3.3,30.1,!0,3.6107),p=P_(a.fontWeight),r=doa(a.padding),u=eoa(a.effects),z=T_(a.cornerRadius,0,10,!0,0);a=M_(a.gradient);if(a=a?a:null){var C=T_(a.x1,0,100,!0,0),E=T_(a.y1,0,100,!0,0),F=T_(a.x2,0,100,!0,100),L=T_(a.y2,0,100,!0,100),aa=O_(a.color1,"#FFF"),qa=O_(a.color2,
"#000");a=new poa(C,E,F,L,aa,qa,T_(a.opacity1,0,100,!0,100),T_(a.opacity2,0,100,!0,0))}else a=null;return new ooa(b,c,d,e,f,k,l,m,n,p,r,u,z,a)},poa=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.C=k;this.D=l},qoa=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},soa=function(a){if(!a)return null;
var b=Q_(a.type,roa,"rect"),c=U_(a.rectRegion,d0),d=U_(a.anchoredRegion,noa);a=U_(a.shapelessRegion,d0);return new qoa(b,c,d,a)},h0=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},toa=function(a,b){this.i=a;
this.g=b},uoa=function(a,b){this.state=a;
this.ref=b},i0=function(a){if(!a)return null;
var b=Q_(a.state,voa);a=N_(a.ref);return b?new uoa(b,a):null},woa=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},xoa=function(a){if(!a)return null;
var b=U_(a.condition,i0),c=U_(a.notCondition,i0),d=R_(a.show_delay,!1);a=R_(a.hide_delay,!1);return b||c?new woa(b,c,d,a):null},yoa=function(a,b,c){(0,g.A)(a.g,g.Sa(b,!1),c);
(0,g.A)(a.l,g.Sa(b,!0),c)},j0=function(a,b,c,d,e,f,k,l,m,n,p,r,u,z){this.id=a;
this.author=b;this.type=c;this.style=d;this.l=e;this.segment=f;this.i=k||[];this.A=l||[];this.g=m;this.u=n;this.o=p;this.data=r;this.Ya=u;this.itct=z},Boa=function(a){if(!a)return null;
var b=N_(a.id),c=N_(a.author),d=Q_(a.type,zoa),e=Q_(a.style,k0),f=P_(M_(a.TEXT)),k=P_(a.data);k=0!=k.length?JSON.parse(k):{};var l=M_(a.segment);var m=l?l:null;m?(N_(m.timeRelative),l=N_(m.spaceRelative),l=(m=U_(m.movingRegion,soa))?new toa(l,m):null):l=null;m=U_(a.action,loa);var n=U_(a.trigger,xoa),p=M_(a.appearance);(p=g0(p?p:null))||(p=g0({}));var r=Q_(a.coordinate_system,Aoa,"video_relative"),u=R_(a.closeable,!0),z=P_(a.log_data);a=P_(a.itct);return b&&d?new j0(b,c,d,e,f,l,m,n,p,r,u,k,z,a):null},
m0=function(a){return l0(a,function(b){return"click"==b.trigger})},l0=function(a,b){return(0,g.Mj)(a.i,b,void 0)},Coa=function(a,b,c){(0,g.A)(a.i,b,c)},Doa=function(a,b){return g.Ya(a.i,b,void 0)},n0=function(a,b,c){(0,g.A)(a.A,b,c)},Eoa=function(a,b){(0,g.B)(a.A,b,void 0)},p0=function(a){return(a=o0(a))?h0(a):null},o0=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},q0=function(a,b){var c=p0(a);
return c&&b?Y_(b,c.i,c.g?c.g:"xy"):1},s0=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;yoa(b,function(d,e){var f=r0(e.state,e.ref);this.i.subscribe(f,(0,g.x)(this.o,this,f,d));this.g[f]=d},this)},r0=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},t0=function(){this.g=!1;
this.u=this.i=null},u0=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new y_(b,c,void 0,void 0,void 0),a.i=b,a.i.fq(),a.u=g.Rd("DIV"),a.u.appendChild(a.i.ga()));
return a.i},v0=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Lb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},w0=function(a,b){var c=g.fo(g.eo.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Foa=function(a,b){var c=w0(a,v0("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=w0(a,v0("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},v0("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=w0(a,v0("feComposite",{"in":c,in2:b,operator:"in"}));return w0(a,v0("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},Goa=function(a,b){var c=w0(a,v0("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=w0(a,v0("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=w0(a,v0("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=w0(a,v0("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=w0(a,v0("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=w0(a,v0("feComposite",{operator:"out","in":c,in2:d}));return w0(a,v0("feComposite",{operator:"over","in":b,in2:c}))},Hoa=function(a,b){return b},Ioa=function(a){var b=
v0("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.A)(a,function(d){a:{switch(d){case "bevel":d=Foa;break a;case "dropshadow":d=Goa;break a}d=Hoa}c=d(b,c)});
return b},Joa=function(a){a=(0,g.Yd)(a,function(b){return b in x0});
g.rb(a,function(b,c){return x0[b]-x0[c]});
return a},Koa=function(a){return g.Ya(a,function(b){return"dropshadow"==b})?new g.kh(0,7,7,0):new g.kh(0,0,0,0)},y0=function(a,b,c){var d=new LZ;
d.moveTo(a.left+b+c,a.top+c);d.Zb(a.left+a.width-b-c,a.top+c);MZ(d,b,b,-90);d.Zb(a.left+a.width-c,a.top+a.height-b-c);MZ(d,b,b,0);d.Zb(a.left+b+c,a.top+a.height-c);MZ(d,b,b,90);d.Zb(a.left+c,a.top+b+c);MZ(d,b,b,180);d.close();return d},z0=function(a,b,c,d){var e=a.u;
e?a=new FZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.C,e.D):(b=a.g,a=new EZ(a.bgColor,d?Math.max(b,.9):b));return a},A0=function(a,b){var c=g.oh(a),d=Koa(b);
g.Pa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.nh(c.left,c.top,c.right-c.left,c.bottom-c.top)},B0=function(a,b,c){if(c.length&&(b=g.Fd(document,"g",void 0,b),b.length)){var d=Joa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Ioa(d),a=0<d.childNodes.length?HZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},C0=function(){t0.call(this);
this.o=0},Loa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},D0=function(){t0.apply(this,arguments)},E0=function(){t0.apply(this,arguments)},F0=function(){C0.apply(this,arguments)},G0=function(a,b,c,d,e){g.D.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Z=e;this.F=!1;this.aa=new AZ(this);g.G(this,this.aa);this.N=this.u=this.C=this.P=this.i=null;this.W=!1;this.ba=this.H=this.I=null;this.nn=new g.zl(this.pD,100,this);g.G(this,this.nn);this.D=new g.M(this.tw,500,this);g.G(this,this.D);this.O=this.l=this.o=null},Moa=function(a,b){var c=(0,g.x)(function(d,e,f){e=f?H0(this,e,(0,g.x)(f,this)):H0(this,e);
this.aa.ca(b,d,e)},a);
c("mouseover","G",a.qx);c("mouseout","F",a.Ag);c("click","D");c("touchend","D")},Noa=function(a){if(a.g.o){if(l0(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Rd("DIV","annotation-close-button"),g.Th(a.o,!1),g.Ep(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.aa.ca(b,"click",H0(a,"E",c));a.aa.ca(b,"touchend",H0(a,"E",c))}},H0=function(a,b,c){return(0,g.x)(function(d){if(this.Z)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Th(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.ge(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Th(e,
!0)}}e=mZ(d.target);d=new g.ud(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.M(b,this.g)},a)},K0=function(a){if(a.i||a.l){var b=p0(a.g);
if(b){var c=I0(a);if(a.i){b=c0(b,c);var d=g.QJ(a.A).getVideoContentRect();g.Rh(a.i,b.width,b.height);g.Hh(a.i,b.left,b.top);a.P=new g.nh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=p0(a.g))&&d?X_(d,e.o,e.g?e.g:"xy"):1;var f=q0(a.g,d);d=a.g.g;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.kh(d,d,d,d));d=new g.kh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.C&&(a.C.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.QJ(a.A).getVideoContentRect();var p=g.VJ(a.A);g.ph(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.u&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=J0(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Rh(a.u,f.width,f.height);g.Hh(a.u,f.left,f.top)}a.o&&(r?b=new g.ud(r.left+
r.width-23-18,a.W?r.top+2:r.top+r.height-18-2):(r=J0(a,18,b,d,e),b=new g.ud(r.left,r.top),g.Rh(a.o,r.width,r.height)),g.Hh(a.o,b));a.N=new g.nh(a.P.left+r.left,a.P.top+r.top,r.width,r.height);a.I=a.aa.ca(g.QJ(a.A),"mousemove",a.AF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.wd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.nh(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.nh(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Rh(a.u,
r.width,r.height),g.Hh(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Hh(a.o,r&&e?new g.ud(b.width-9,-9):r?new g.ud(b.width-9,45<b.height?9:b.height-9):e?new g.ud(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.ud(45<b.width?b.width-9-18:-9,b.height-9):new g.ud(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.g;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.QJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
q0(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Hd("annotation-link-icon",a))?oZ(b):!1;e=(d=g.Hd("annotation-close-button",a))?oZ(d):!1;r&&g.Th(b,!1);e&&g.Th(d,!1);m=f="";if(n=g.Hd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=Mna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Th(d,!0);r&&g.Th(b,!0)}}}},J0=function(a,b,c,d,e){var f=0<e;
b=new g.nh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.W=!0);return b},L0=function(a){return"label"!=a.g.style||a.l.g},I0=function(a){var b=g.QJ(a.A).getVideoContentRect();
if("player_relative"==a.g.u){var c=g.QJ(a.A).getPlayerSize();b=new g.nh(-b.left,-b.top,c.width,c.height)}else b=new g.nh(0,0,b.width,b.height);return new e0(b,a.O?p0(a.O):null)},M0=function(a,b){return b?new g.nh(a.x+b.left,a.y+b.top,b.width,b.height):null},N0=function(a,b,c){g.D.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;Ooa(b,a)},Ooa=function(a,b){Eoa(a,function(c){return new s0(a.id,c,b)})},O0=function(a){a.i.unsubscribe("resize",a.ox,a);
a.i.unsubscribe("onVideoAreaChange",a.ez,a)},P0=function(a){a.g&&(a.g.stop(),a.g=null)},Q0=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Poa=function(a,b){this.merchant=a;
this.price=b},Qoa=function(a){this.g=a;
this.i={}},Roa=function(a){var b={};
b=(b["iv-event"]=1,b);kZ(a.g,b,void 0)},U0=function(a,b,c,d){if(b){var e=R0(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=S0(a,"cta_annotation_shown",e,c);T0(a,e,Soa(b,d))}},V0=function(a,b,c,d,e,f){if(b){var k=R0(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.fc(k,d);b=S0(a,"cta_annotation_clicked",k,e);T0(a,k,b,c,f)}},W0=function(a,b){if(b){var c=R0(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=S0(a,"cta_annotation_closed",c);T0(a,c,d)}},Soa=function(a,b){return b?(0,g.B)(a,g.Sa(function(c,d){return g.cn(d,c)},b)):a},S0=function(a,b,c,d){d=d?g.ib(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Q(g.X(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.vu){if((b=a.vu[b])&&g.av(b)){a=g.Xc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Fn){b=g.nq(a.Fn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},T0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.A)(c||[],function(n){f++;
g.Zq(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));kZ(a.g,b,m)},R0=function(a,b){var c={};
if(b){var d=new g.Sm(b);(0,g.A)(d.Gd(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.X(a.g).playerStyle;return c},X0=function(a,b,c,d,e){e=R0(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;T0(a,e,d)},Y0=function(a,b,c,d){c&&(c=R0(a,c),c["iv-event"]=b,T0(a,c,d))},Toa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.xb=c;this.videoData=d;this.logger=e;this.Y=f;this.i=k},Z0=function(a,b){this.g=a;
this.o=b;this.i=new g.Ln},Voa=function(a,b){var c=[];
(0,g.A)(b.choices,function(k){c.push(Uoa(this,b,k))},a);
var d={B:"ul",L:{role:"radiogroup"},J:c},e={};b.Pd&&(e["aria-label"]=g.bN('\u0427\u0442\u043e\u0431\u044b \u043f\u0440\u0438\u043d\u044f\u0442\u044c \u0443\u0447\u0430\u0441\u0442\u0438\u0435 \u0432 \u043e\u043f\u0440\u043e\u0441\u0435 "$POLL_TITLE", \u043d\u0443\u0436\u043d\u043e \u0432\u043e\u0439\u0442\u0438 \u0432 \u0430\u043a\u043a\u0430\u0443\u043d\u0442.',{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{B:"div",G:"iv-card-content",J:[$0(a,"h2",e,b.title),{B:"form",J:[{B:"fieldset",
J:[d]}]}]}];b.Pd&&(f.push("iv-card-unavailable"),d.push({B:"div",V:["iv-card-sign-in"],J:[{B:"h2",U:"\u0425\u043e\u0442\u0438\u0442\u0435 \u043f\u0440\u043e\u0439\u0442\u0438 \u043e\u043f\u0440\u043e\u0441?"},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:W_(b.Pd)},J:[{B:"span",V:["iv-button-content"],U:"\u0412\u043e\u0439\u0442\u0438"}]}]}));f=new g.W({B:"div",V:f,J:d});d=f.element;a1(b,d);Rna(a.g.g,d,g.Sa(a.u,b),a);(0,g.A)(g.Gd("iv-card-poll-choice-input",d),function(k){this.g.g.ca(k,"focus",
g.Sa(this.l,!0));this.g.g.ca(k,"blur",g.Sa(this.l,!1))},a);
b.Pd&&(d=g.Hd("iv-card-sign-in-button",d),a.o(d,b.Pd,b.id,b.Wb,b.Ya,b.pd.click,5));return f},e1=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.OM?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.YD&&b.zu?{B:"span",V:d,L:e,U:b.zu}:"";c={B:"div",V:["iv-card",c],J:[{B:"a",G:"iv-click-target",L:{href:W_(b.url)},J:[b1(b.al,d?{B:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{B:"div",G:"iv-card-content",J:[{B:"h2",G:"iv-card-primary-link",U:b.title},c1(a,b)]}]}]};c=new g.W(c);d1(a,c,b);return c},f1=function(a,b){return b.customMessage?$0(a,"div",
"iv-card-message",b.customMessage):""},b1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{B:"div",G:"iv-card-image",L:{style:c},J:d}},c1=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.A)(b.metaInfo,function(d){c.push($0(this,"li","",d))},a);
return{B:"ul",G:"iv-card-meta-info",J:c}},Uoa=function(a,b,c){return{B:"li",
G:Q0(b,c.index),J:[{B:"label",J:[{B:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.id.replace(/[^a-z0-9-]/gi,"-")+c.index.toString(),value:c.index.toString(),"data-poll-choice-index":c.index.toString()}},{B:"span",G:"iv-card-poll-choice-text",J:[{B:"span",G:"iv-card-poll-choice-percent"},$0(a,"span",void 0,c.desc)]}]},{B:"div",G:"iv-card-poll-result",J:[{B:"div",G:"iv-card-poll-result-bar"}]}]}},$0=function(a,b,c,d){c?g.Fa(c)?c={"class":c}:g.Ma(c)&&(c={"class":c.join(" ")}):
c={};
c.dir=g.Mn(a.i,d);return{B:b,L:c,U:d}},g1=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.bp&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.bp+");");d.dir=g.Mn(a.i,b.customMessage);var e=[{B:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",V:c,L:d,J:e}},a1=function(a,b){var c=0;
(0,g.A)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Hd(Q0(a,e.index),b);e=e.count/c;null==a.ge&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.ge==d);f.getElementsByTagName("input")[0].checked=a.ge==d;var k=Math.floor(100*e).toFixed(0),l=g.Hd("iv-card-poll-choice-percent",f);g.be(l,g.bN("$PERCENT%",{PERCENT:k}));f=g.Hd("iv-card-poll-result-bar",f);g.zh(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.ge);g.K(b,"iv-card-poll-expanded",
null!=a.ge&&1<a.choices.length)},d1=function(a,b,c,d,e){c.Pd&&h1(a,g.Gd("iv-card-sign-in-button",b.element),c,c.Pd,e);
c.url&&h1(a,g.Gd("iv-click-target",b.element),c,c.url,d)},h1=function(a,b,c,d,e){(0,g.A)(b,function(f){if(e){var k=(0,g.x)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.ca(f,"click",k)}else d&&this.o(f,d,c.id,c.Wb,c.Ya,c.pd.click,5)},a)},i1=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},k1=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=j1(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},j1=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},Woa=function(a){a=W_(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!k1(a))||(b=g.Qg(g.Sg(5,a))||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.lq(a);if(!b||!b.v)return null;if(b=b.t)return i1(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.jq(a[1]))&&a.t?i1(a.t):-1},l1=function(a){a=W_(a);
a=a.replace(/https?:\/\//g,"");return k1(a)?(a=g.lq(a))&&a.v?a.v:null:null},Xoa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},m1=function(a,b){return b?b:k1(a)?"current":"new"},n1=function(a,b){g.D.call(this);
this.Ba=a;this.context=b;this.jt=!1;this.X=0},Yoa=function(a){return(0,g.H)()-a.X},Zoa=function(a,b,c,d,e,f){var k=W_(b);
if(k){var l=m1(k,b.target),m=(0,g.x)(function(){b.g&&this.context.Y.pauseVideo();var p=this.context.videoData.Mb||!1,r=g.lq(k||"");p&&r&&(r.v||r.list)?g.LX(this.context.Y.app,r.v,c,r.list,!1,void 0):g.jL(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=Yoa(a);V0(a.context.logger,d,m,n,e,f);k1(k)||(a=g.$s(),d=c.itct,a&&d&&g.Ns(a,g.Js(d)))}},q1=function(a,b,c){n1.call(this,b,c);
var d=this;this.i=a;this.R=null;this.W=this.wa=this.u=this.va=!1;this.ba=null;this.N=new g.M(g.Ja,c.xb.ed?4E3:3E3);g.G(this,this.N);this.ka=new g.M(g.Ja);g.G(this,this.ka);this.D=new Z0(c,(0,g.x)(this.Ki,this),(0,g.x)(this.Mm,this));this.F=new g.W({B:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{B:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{B:"span",G:"iv-drawer-header-text"},{B:"button",V:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"\u0421\u043a\u0440\u044b\u0442\u044c \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438",
tabindex:"0"}}]},{B:"div",G:"iv-drawer-content"}]});g.G(this,this.F);this.A=this.F.element;this.ua=new g.OP(this.F,330);g.G(this,this.ua);this.xa=g.Hd("iv-drawer-header-text",this.A);this.o=g.Hd("iv-drawer-content",this.A);this.l=[];this.ma=this.O=this.C=this.Z=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.wa&&o1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wa=d.u)&&p1(d)});
this.P=this.H=this.fa=null},$oa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c){var d=b.data.tracking||{};d={PD:d.impression,click:d.click,close:d.close,yM:d.teaser_impression,Ms:d.teaser_click};var e=b.data.tracking_params||{},f=null;switch(c){case "collaborator":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Wb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,mf:e.card?g.Js(e.card):null,Ye:e.teaser?g.Js(e.teaser):
null,ce:e.icon?g.Js(e.icon):null,channelId:b.data.channel_id,customMessage:b.data.custom_message,SL:b.data.image_url,title:b.data.title,metaInfo:b.data.meta_info,url:V_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})};r1(a,d);break;case "episode":case "movie":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||
!1,Wb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,mf:e.card?g.Js(e.card):null,Ye:e.teaser?g.Js(e.teaser):null,ce:e.icon?g.Js(e.icon):null,al:b.data.image_url,zu:b.data.badge_symbol||"",priceText:b.data.price_text||"",title:b.data.title,metaInfo:b.data.meta_info,YD:!!b.data.is_paygated,OM:!!b.data.user_has_entitlement,url:V_({target:b.data.target||"new",value:b.data.url})};r1(a,d);break;case "playlist":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,
teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Wb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,mf:e.card?g.Js(e.card):null,Ye:e.teaser?g.Js(e.teaser):null,ce:e.icon?g.Js(e.icon):null,al:b.data.image_url,playlistVideoCount:b.data.playlist_video_count,customMessage:b.data.custom_message,title:b.data.title,metaInfo:b.data.meta_info,url:V_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})};r1(a,
d);break;case "poll":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Wb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,mf:e.card?g.Js(e.card):null,Ye:e.teaser?g.Js(e.teaser):null,ce:e.icon?g.Js(e.icon):null,title:b.data.title,choices:b.data.choices,ge:b.data.hasOwnProperty("old_vote")?b.data.old_vote:null,Pd:b.data.signin_url?V_({target:"current",
value:b.data.signin_url}):null,XM:b.data.hasOwnProperty("xsrf_token")?b.data.xsrf_token:null};r1(a,d);break;case "productListing":b.data.signin_url&&(f=V_({target:"current",value:b.data.signin_url}));c=[];for(var k=b.data.offers||[],l=0;l<k.length;l++)c.push(new Poa(g.bd(k[l].merchant),g.bd(k[l].price)));d={yQ:!1,id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||
!1,Wb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,mf:e.card?g.Js(e.card):null,Ye:e.teaser?g.Js(e.teaser):null,ce:e.icon?g.Js(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain,showLinkIcon:b.data.show_link_icon,bp:b.data.button_icon_url,title:b.data.title,customMessage:b.data.custom_message,url:V_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url}),Pd:f,tA:b.data.signin_title||null,sA:b.data.signin_message||null,offers:c};
r1(a,d);break;case "simple":b.data.signin_url&&(f=V_({target:"current",value:b.data.signin_url}));d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Wb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,mf:e.card?g.Js(e.card):null,Ye:e.teaser?g.Js(e.teaser):null,ce:e.icon?g.Js(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain,
showLinkIcon:b.data.show_link_icon,bp:b.data.button_icon_url,title:b.data.title,customMessage:b.data.custom_message,url:V_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url}),Pd:f,tA:b.data.signin_title||null,sA:b.data.signin_message||null};r1(a,d);break;case "video":d={id:b.id,Ya:b.Ya,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||
!1,Wb:b.data.session_data||{},sponsored:b.data.sponsored||!1,pd:d,mf:e.card?g.Js(e.card):null,Ye:e.teaser?g.Js(e.teaser):null,ce:e.icon?g.Js(e.icon):null,al:b.data.image_url,videoDuration:b.data.video_duration||null,customMessage:b.data.custom_message,title:b.data.title,metaInfo:b.data.meta_info,isLiveNow:!!b.data.is_live_now,url:V_({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})},r1(a,d)}}},apa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,
0x8000000000000,"",function(){o1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){p1(a)});
var c=b.data.headerText;g.be(a.xa,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.fa=g.Js(b.data.trackingParams);a.P=g.Js(b.data.closeTrackingParams);a.H=g.Js(b.data.iconTrackingParams)},t1=function(a,b){var c=bpa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Fb.id),g.Xd(c.kp),g.eb(a.l,c),a.Kl(),s1(a))},o1=function(a,b,c,d){if(!a.u){a.ua.show();
a.Z=new g.M(function(){g.J(a.context.Y.getRootNode(),"ytp-iv-drawer-open")},0);
a.Z.start();a.ba=g.Mr(a.o,"mousewheel",(0,g.x)(a.YE,a));a.u=!0;a.X=(0,g.H)();X0(a.context.logger,a.R,7,void 0,d&&d.Fb?d.Fb.Ya:void 0);var e=g.$s();e&&a.fa&&a.P&&BZ(e,[a.fa,a.P]);var f={TRIGGER_TYPE:b};(0,g.A)(a.l,function(k){k.Qw||(k.Qw=!0,U0(a.context.logger,k.Fb.Ya,k.Fb.pd.PD,f));e&&BZ(e,[k.Fb.mf])});
lZ(a.i);c&&(a.C=new g.M(function(){a.ea=a.O;a.ma.focus()},330),a.C.start())}},p1=function(a){a.u&&(a.ua.hide(),g.Nr(a.ba),a.ba=null,g.Sn(a.context.Y.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,lZ(a.i),a.C&&a.C.stop(),a.C=new g.M(function(){a.ea&&(a.ea.focus(),a.ea=null)},330),a.C.start())},cpa=function(a){var b=g.Hd("iv-drawer-close-button",a.A);
a.context.g.ca(b,"click",a.pC,a);a.context.g.ca(a.o,"touchend",function(){a.N.start()});
a.context.g.ca(a.o,"scroll",a.zC,a);a.context.i.subscribe("onHideControls",function(){a.W=!0});
a.context.i.subscribe("onShowControls",function(){a.W=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.W=g.Qn(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.Op("iv-button-shown",a.iE,a));a.I.push(g.Op("iv-button-hidden",a.hE,a));a.I.push(g.Op("iv-teaser-shown",a.lE,a));a.I.push(g.Op("iv-teaser-hidden",a.kE,a));a.I.push(g.Op("iv-teaser-clicked",a.jE,a))},r1=function(a,b){a.va||(g.Rn(a.ga(),["html5-stop-propagation",
"iv-drawer-manager"]),g.dK(a.i,a.A,5),cpa(a),a.O=g.Hd("ytp-cards-button",a.i.getRootNode()),a.ma=g.Hd("iv-drawer-close-button",a.A),a.va=!0);t1(a,b.id);var c=dpa(a,b);if(c){var d={Fb:b,kp:c.element,Qw:!1},e=epa(a,d);g.lb(a.l,e,0,d);c.g(a.o,e);a.Kl();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Sa(a.kM,d)):(c=1E3*a.context.Y.getCurrentTime(),5E3>c&&c>b.startMs&&a.eA(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Sa(a.eA,d)),s1(a))}},dpa=function(a,b){switch(b.type){case "simple":var c=
a.D,d=b.displayDomain?{B:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",e=g1(c,b),f=["iv-card"];b.Pd&&f.push("iv-card-unavailable");d=[{B:"a",G:"iv-click-target",L:{href:W_(b.url)},J:[b1(b.imageUrl,d),{B:"div",G:"iv-card-content",J:[$0(c,"h2",void 0,b.title),e]}]}];b.Pd&&d.push({B:"div",V:["iv-card-sign-in"],J:[$0(c,"h2",void 0,b.tA||""),{B:"p",U:b.sA},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:W_(b.Pd)},J:[$0(c,"span","iv-button-content","\u0412\u043e\u0439\u0442\u0438")]}]});f=new g.W({B:"div",V:f,J:d});d1(c,
f,b,void 0,void 0);return f;case "collaborator":return c=a.D,f={B:"div",V:["iv-card","iv-card-channel"],J:[{B:"a",V:["iv-click-target"],L:{href:W_(b.url),"data-ytid":b.channelId},J:[b1(b.SL),{B:"div",G:"iv-card-content",J:[f1(c,b),{B:"h2",G:"iv-card-primary-link",U:b.title},c1(c,b)]}]}]},f=new g.W(f),d1(c,f,b),f;case "episode":return e1(a.D,b,"iv-card-episode");case "movie":return e1(a.D,b,"iv-card-movie");case "playlist":return c=a.D,f={B:"div",V:["iv-card","iv-card-playlist"],J:[{B:"a",G:"iv-click-target",
L:{href:W_(b.url)},J:[b1(b.al,{B:"div",G:"iv-card-image-overlay",J:[{B:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{B:"div",G:"iv-card-content",J:[f1(c,b),$0(c,"h2","iv-card-primary-link",b.title),c1(c,b)]}]}]},f=new g.W(f),d1(c,f,b),f;case "poll":return Voa(a.D,b);case "productListing":c=a.D;e=0!=b.offers.length;f=["iv-card"];d="";var k=g1(c,b);e&&(f.push("iv-card-product-listing"),d="iv-card-primary-link",e=b.offers[0],k=[],e.price&&k.push({B:"div",G:"iv-card-offer-price",
U:e.price}),e.merchant&&k.push({B:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={B:"div",J:k});f={B:"div",V:f,L:{tabindex:"0"},J:[{B:"a",V:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:W_(b.url),"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",J:[b.sponsored?{B:"div",G:"iv-card-sponsored",J:["\u0420\u0435\u043a\u043b\u0430\u043c\u0430",{B:"div",G:"iv-ad-info-container",J:[{B:"div",G:"iv-ad-info",U:"{{adInfo}}"},{B:"div",G:"iv-ad-info-icon-container",
J:[{B:"div",G:"iv-ad-info-icon"},{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",L:{href:W_(b.url)},J:[$0(c,"h2",d,b.title),k]}]}]};f=new g.W(f);d=g.Sd("span");g.be(d,"\u042d\u0442\u043e \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u043d\u0430\u044f \u0440\u0435\u043a\u043b\u0430\u043c\u0430. \u0415\u0435 \u043f\u043e\u043a\u0430\u0437 \u043c\u043e\u0436\u0435\u0442 \u043e\u043f\u043b\u0430\u0447\u0438\u0432\u0430\u0442\u044c\u0441\u044f \u043f\u0440\u043e\u0434\u0430\u0432\u0446\u043e\u043c.");
f.kb(d,"adInfo");d1(c,f,b);return f;case "video":return c=a.D,f=b.isLiveNow?{B:"span",V:["yt-badge","yt-badge-live"],U:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"}:"",f={B:"div",V:["iv-card","iv-card-video"],J:[{B:"a",G:"iv-click-target",L:{href:W_(b.url)},J:[b1(b.al,b.videoDuration?{B:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{B:"div",G:"iv-card-content",J:[f1(c,b),$0(c,"h2","iv-card-primary-link",b.title),c1(c,
b),f]}]}]},f=new g.W(f),d1(c,f,b),f}return null},epa=function(a,b){if(0==a.l.length)return 0;
var c=g.Za(a.l,function(d){return b.Fb.startMs>d.Fb.startMs||b.Fb.startMs==d.Fb.startMs&&b.Fb.timestamp>=d.Fb.timestamp?!0:!1});
return-1==c?0:c+1},fpa=function(a){return a.g?"productListing"==a.g.Fb.type:(0,g.jj)(a.l,function(b){return"productListing"==b.Fb.type})},s1=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",fpa(a))},u1=function(a,b){if(a.F.Da()){var c=new wZ([0,
a.o.scrollTop],[0,b.kp.offsetTop],600,Qna);a.context.l.ca(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.ca(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.JC(a.F,!0),a.o.scrollTop=b.kp.offsetTop,g.JC(a.F,!1)},v1=function(a){return a.g&&a.g.Fb?a.g.Fb:a.l[0]&&a.l[0].Fb?a.l[0].Fb:null},bpa=function(a,b){return g.Ya(a.l,function(c){return c.Fb.id==b})},w1=function(a,b,c){n1.call(this,a,b);
this.annotation=c;this.isActive=!1},gpa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},x1=function(a,b,c){w1.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.C=this.A=null},y1=function(a,b,c){w1.call(this,a,b,c);
this.F=this.u=this.H=!1;this.C=5E3;this.o=null;this.D=g.Rd("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.M(function(){this.g.setAttribute("aria-hidden",!0);g.Th(this.l,!1);g.Th(this.i,!0)},700,this);
g.G(this,this.A)},hpa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.ga().setAttribute("aria-hidden",!0);a.ga().setAttribute("aria-label","\u041f\u0440\u043e\u0434\u0432\u0438\u0436\u0435\u043d\u0438\u0435");a.ga().tabIndex=0;var e=a.annotation.Ib(),f=b.image_url;if(f){var k=g.Rd("DIV",["iv-promo-img","iv-click-target"]);f=g.Rd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&
!b.is_live?(f=g.Rd("SPAN","iv-promo-video-duration",b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Rd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Ki(k,e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c)}e?(f=g.Rd("A","iv-promo-txt"),g.Uc(f,W_(e)),a.g=f):a.g=g.Rd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_1));var m=g.Rd("P",null,g.Rd("SPAN","iv-promo-link",
b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.Q(a.context.xb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Rd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Rd("BUTTON",["iv-button","iv-promo-button"],g.Rd("SPAN","iv-button-content",f));var p=g.Rd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Ki(a.ga(),e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c)}g.J(a.g,"iv-click-target");e&&
a.Ki(a.g,e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c);break;case "playlist":case "video":l=g.Rd("P",null,g.Rd("SPAN",null,b.text_line_1)),m=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Rd("SPAN",["yt-badge","iv-promo-badge-live"],"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415")),g.J(a.g,"iv-click-target"),e&&a.Ki(a.g,e,a.annotation.id,b.session_data,a.annotation.Ya,void 0,c),d.push("iv-promo-video")}l&&
a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);c=g.Rd("DIV","iv-promo-actions");a.i=g.Rd("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c";a.context.g.ca(a.i,"click",g.Sa(a.hq,5E3),a);c.appendChild(a.i);g.Th(a.i,!1);a.context.g.ca(a.ga(),"mouseover",a.rD,a);a.context.g.ca(a.ga(),"mouseout",a.qD,a);a.context.g.ca(a.ga(),"touchend",g.Sa(a.hq,5E3),a);a.l=g.Rd("BUTTON",["iv-promo-close","ytp-button"]);
a.l.title="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";a.context.g.ca(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.jD:a.iD,a);c.appendChild(a.l);g.Rn(a.ga(),d);k&&(a.ga().appendChild(k),n&&k.appendChild(n));a.ga().appendChild(a.D);a.ga().appendChild(c)},z1=function(a){a.u||a.F||a.o||(g.J(a.ga(),"iv-promo-collapsed"),a.u=!0,a.A.start())},A1=function(a){a.A.stop();
a.u&&(g.Tn(a.ga(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Th(a.i,!1),g.Th(a.l,!0))},C1=function(a,b){a.o||(a.o=g.Gg(function(){B1(this);
z1(this)},b,a))},B1=function(a){a.o&&(g.v.clearTimeout(a.o),a.o=null)},D1=function(a){g.rK.call(this,a);
this.I=!1;this.H=0;this.i={};this.P={};this.D=new Qoa(a);this.A=new g.us(this);g.G(this,this.A);this.C=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.x)(this.M,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.x)(this.M,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.x)(this.M,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.x)(this.M,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.x)(this.M,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.UI,this);this.subscribe("onShowControls",this.NK,this);this.subscribe("presentingplayerstatechange",this.XJ,this);this.subscribe("resize",this.un,this);this.subscribe("G",this.GE,this);this.subscribe("F",this.Ag,this);this.subscribe("D",this.QH,this);this.subscribe("E",this.tI,this);g.X(this.player).I.subscribe("vast_info_card_add",this.dz,this);this.R=new g.us(this);g.G(this,this.R);this.R.K(this.player,g.SD("annotations_module"),this.EE);this.R.K(this.player,
"crx_annotations_module",this.FE);this.O=g.Rd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.W=g.Rd("DIV","video-custom-annotations");this.u=new g.W({B:"div",V:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.u);g.dK(this.player,this.u.element,4);this.u.hide();this.o=new g.W({B:"div",V:["ytp-iv-video-content"]});g.G(this,this.o);g.Ud(this.o.element,g.Rd("DIV","video-annotations",this.O,this.W));this.F=this.g=null;this.N=[];ipa(this)&&this.load();var b=g.Sd("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},E1=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},ipa=function(a){var b=g.X(a.player);
a=a.player.getVideoData();return 1==(b.Uf||a.Uf)&&!a.bB||null!==b.I.get(a.videoId)},F1=function(a,b,c){a.I=!0;
a.C=g.Eq(b,c)},G1=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(G1(a,e))}return c},H1=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},kpa=function(a,b){var c=jpa(a,b);
if(!c&&"marker"!=b.type)return null;n0(b,function(e){e=(0,g.x)(this.lL,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new N0(a.ua,b,c);g.G(d,c);return d},lpa=function(a,b){var c=g.Rd("DIV",["annotation",
"annotation-type-custom"]);g.Th(c,!1);var d=null;switch(b.type){case "branding":if(g.X(a.player).cj)break;a.u.element.appendChild(c);d=new x1(c,I1(a),b);break;case "promotion":g.dK(a.player,c,4),d=new y1(c,I1(a),b)}d&&d.Un();return d},mpa=function(a){var b=a.player.getVideoData();
if(b.Ed){var c=g.X(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Dc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Dc.gaming="1");e.Xc=(0,g.x)(function(f,k,l){H1(this,f,k)||(f=g.yq(l)&&l.responseXML?l.responseXML:null)&&J1(this,f)},a,a.H,b.videoId);
g.bq()&&(e.Xc=K1(a,e.Xc));e.ub={ic_only:"1"};L1(e,d);a.I=!0;g.Eq(b.Ed,e)}}},L1=function(a,b){a.method="POST";
a.ub=a.ub||{};b.Pl&&(a.ub.ic_coll=b.Pl);b.Ql&&(a.ub.ic_xml=b.Ql);b.Ts&&(a.ub.ic_track=b.Ts)},M1=function(a){var b=new g.W({B:"div"});
g.Th(b.element,!1);var c=new q1(a.player,b.element,I1(a));g.G(c,b);b.g(a.u.element);c.Un();return c},I1=function(a){if(!a.F){var b=new AZ(a);
g.G(a,b);var c=new g.$m(a);g.G(a,c);a.F=new Toa(b,c,g.X(a.player),a.player.getVideoData(),a.D,a.player,a.ua)}return a.F},J1=function(a,b){var c=!1;
npa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=G1(a,d[e]),k=null;try{k=Boa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=lpa(a,k))g.G(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=M1(a),g.G(a,a.g)),"card"==k.type?$oa(a.g,k):apa(a.g,k),c=!0;else if(f=kpa(a,k))g.G(a,f),a.i[k.id]=f}}c&&(lZ(a.player),a.un());g.Lb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.O=m.annotation)}},a)},opa=function(a,b){var c=!1;
a.g||(a.g=M1(a),g.G(a,a.g));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())c=!0;c&&(lZ(a.player),a.un())},npa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.$s();
if(b){var c=g.Zs();c&&g.Ls(b,c,[g.Js(a)])}}},ppa=function(a,b,c,d){d?N1(a,b,c):O1(a,b,c)},O1=function(a,b,c){if(b=a.i[b])P0(b),c&&c.i?(a=(0,g.x)(a.rw,a,b),b.g=new g.M(a,2E3),b.g.start()):a.rw(b)},N1=function(a,b,c){if(b=a.i[b])P0(b),c&&c.o?(a=(0,g.x)(a.pA,a,b),b.g=new g.M(a,2E3),b.g.start()):a.pA(b)},P1=function(a,b){var c=a.player.getVideoData();
if(!c.El)return!1;var d=W_(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!k1(d))return!1;d=g.lq(d);return d.list||d.p?!1:(d=l1(b))?c.videoId==d?!0:"new"!=b.target&&g.X(a.player).i?!0:!1:!1},jpa=function(a,b){if(qpa(b)){var c=b.o||l0(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new G0(b,(0,g.x)(a.O.appendChild,a.O),a.player,a.ua,c)}return null},qpa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in k0)if(a.style==k0[b])return!0;return!1},Q1=function(a,b,c,d){a.M(r0(b,d),c,d)},K1=function(a,b){return(0,g.x)(function(){if(!this.da()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.N.push(g.$p(b))}},a)};
g.KJ.prototype.Gi=g.da(14,function(a,b){var c=g.LJ(this).l;c&&c.Gi(a,b)});
g.go.prototype.fq=g.da(0,function(){this.i=this.N.createElement("DIV")});
var Jna=/[^\d]+$/,Kna={cm:1,"in":1,mm:1,pc:1,pt:1},Lna={em:1,ex:1},qZ={},rZ=null;g.y(vZ,g.sf);g.y(wZ,g.Vn);g.h=wZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;sZ(this);this.startTime=a=(0,g.H)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Vd("play");-1==this.g&&this.Vd("resume");this.g=1;var b=g.Ra(this);b in qZ||(qZ[b]=this);tZ();uZ(this,a);return!0};
g.h.stop=function(a){sZ(this);this.g=0;a&&(this.progress=1);xZ(this,this.progress);this.Vd("stop");this.l()};
g.h.pause=function(){1==this.g&&(sZ(this),this.g=-1,this.Vd("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Vd("destroy");wZ.Wa.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Lr=function(){this.Vd("animate")};
g.h.Vd=function(a){this.dispatchEvent(new vZ(a,this))};
g.y(yZ,wZ);yZ.prototype.u=g.Ja;yZ.prototype.Lr=function(){this.u();yZ.Wa.Lr.call(this)};
yZ.prototype.l=function(){this.u();yZ.Wa.l.call(this)};
yZ.prototype.o=function(){this.u();yZ.Wa.o.call(this)};
g.y(zZ,yZ);zZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(AZ,g.D);AZ.prototype.ca=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Mr(a,b,c);this.g.push(a);return a};
AZ.prototype.Nm=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Wr(a,b,c);this.g.push(a);return a};
AZ.prototype.La=function(a){g.Nr(a);g.eb(this.g,a)};
AZ.prototype.T=function(){g.Nr(this.g);this.g.length=0;g.D.prototype.T.call(this)};g.y(DZ,g.Sf);g.h=DZ.prototype;g.h.Yp=null;g.h.Sj=null;g.h.ga=function(){return this.Sj};
g.h.addEventListener=function(a,b,c,d){g.Cf(this.Sj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Mf(this.Sj,a,b,c,d)};
g.h.T=function(){DZ.Wa.T.call(this);var a=this.Sj;if(a)if(g.vf(a))a.le&&g.zf(a.le);else if(a=g.Ff(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Nf(d[e])&&++b}};g.y(IZ,DZ);IZ.prototype.fill=null;g.y(KZ,DZ);LZ.prototype.De=null;LZ.prototype.xd=null;LZ.prototype.Wk=!0;var Tna=[2,2,6,6,0];g.h=LZ.prototype;g.h.clear=function(){this.Ta.length=0;this.Ca.length=0;this.Sd.length=0;delete this.De;delete this.xd;delete this.Wk;return this};
g.h.moveTo=function(a,b){0==g.Wa(this.Ta)?this.Sd.length-=2:(this.Ta.push(0),this.Ca.push(1));this.Sd.push(a,b);this.xd=this.De=[a,b];return this};
g.h.Zb=function(a){var b=g.Wa(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ca.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Sd.push(c,d)}this.Ca[this.Ca.length-1]+=b/2;this.xd=[c,d]};
g.h.close=function(){var a=g.Wa(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ca.push(1),this.xd=this.De);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ca=this.Ca.concat();a.Sd=this.Sd.concat();a.De=this.De&&this.De.concat();a.xd=this.xd&&this.xd.concat();a.Wk=this.Wk;return a};
g.h.transform=function(a){if(!this.Wk)throw Error("Non-simple path");a.transform(this.Sd,0,this.Sd,0,this.Sd.length/2);this.De&&a.transform(this.De,0,this.De,0,1);this.xd&&this.De!=this.xd&&a.transform(this.xd,0,this.xd,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.y(NZ,IZ);g.y(v_,g.go);v_.prototype.o=null;v_.prototype.Hj=function(){return this.fh?g.Sh(this.ga()):g.Ha(this.width)&&g.Ha(this.height)?new g.wd(this.width,this.height):null};
v_.prototype.resume=function(){};g.y(FZ,JZ);g.y(EZ,JZ);g.y(w_,KZ);w_.prototype.clear=function(){g.Vd(this.ga())};
w_.prototype.setSize=function(a,b){var c=this.ga(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.y(x_,NZ);var A_;g.y(y_,v_);var Wna=0;g.h=y_.prototype;g.h.fq=function(){var a=GZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=GZ(this,"g");this.C=GZ(this,"defs");this.o=new w_(b,this);a.appendChild(this.C);a.appendChild(b);this.i=a;this.l&&(this.ga().setAttribute("preserveAspectRatio","none"),this.R?this.RA():this.ga().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.RA=function(){if(this.fh){var a=this.Hj();0==a.width?this.ga().style.visibility="hidden":(this.ga().style.visibility="",this.o.ga().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Rh(this.ga(),a,b)};
g.h.Hj=function(){if(!g.Bh)return this.fh?g.Sh(this.ga()):y_.Wa.Hj.call(this);var a=this.width,b=this.height,c=g.Fa(a)&&-1!=a.indexOf("%"),d=g.Fa(b)&&-1!=b.indexOf("%");if(!this.fh&&(c||d))return null;if(c){var e=this.ga().parentNode;var f=g.Sh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ga().parentNode,f=f||g.Sh(e),b=parseFloat(b)*f.height/100);return new g.wd(a,b)};
g.h.clear=function(){this.o.clear();g.Vd(this.C);this.g={}};
g.h.vj=function(){y_.Wa.vj.call(this);this.R&&this.P.La(Xna(),"tick",this.RA)};
g.h.T=function(){delete this.g;delete this.C;delete this.o;this.P.dispose();delete this.P;y_.Wa.T.call(this)};g.t(C_,g.rK);g.h=C_.prototype;
g.h.load=function(){g.rK.prototype.load.call(this);if(!E_(g.X(this.player).playerStyle)){var a=g.FB(this.player.getVideoData());if(a)a=B_(a,D_(this)),F_(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Xc:(0,g.x)(this.KI,this,a),Dc:{v:a},withCredentials:!0};"gaming"==g.X(this.player).playerStyle&&(a.Dc.gaming="1");this.P&&(a.Dc.ptype="embedded");var c=this.player.getVideoData().qv;c&&(a.ub={ad_tracking:c});if(b=g.EB(b))if(b=g.Dc(b),b=g.Ac(b))this.o=
g.Eq(b,a)}}};
g.h.unload=function(){F_(this,null);this.o&&(this.o.abort(),this.o=null);g.rK.prototype.unload.call(this)};
g.h.wc=function(a,b){if(!E_(g.X(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=B_(b,"new");F_(this,c);return!0}return null};
g.h.getOptions=function(){return E_(g.X(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.KI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=B_(c,D_(this)))}F_(this,c)};
g.h.ib=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<R1.length;f++){var k=Math.abs(b.width-R1[f]);if(-1==e||d>=k)e=f,d=k}d=S1[e];this.l&&g.zh(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Rh(e.element,Math.round(k.width*a.width),f);g.Hh(e.element,m,n);g.Tn(e.element,rpa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Tn(e.element,S1);g.J(e.element,d);(e=g.Fd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zh(e,"height",f+"px")}}}}};
g.h.IE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.TJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(K_(this,this.i.impressionUrls),(a=g.$s())&&this.i.visualElement&&g.Ms(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.C[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");K_(this,c.impressionUrls);
(b=g.$s())&&g.Ms(b,c.visualElement);g.X(this.player).rb&&this.player.la("endscreenelementshown",a)}};
g.h.JE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Sn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Sn(b,"ytp-ce-shown");g.X(this.player).rb&&this.player.la("endscreenelementhidden",a)}};
g.h.AL=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c in b.g)g.Tn(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Fy=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Qn(c,"ytp-ce-element");){g.Qn(c,"subscribe-label")&&L_(this,a);if(g.Qn(c,"ytp-ce-channel-subscribe"))return;c=g.$d(c)}if(!c||g.Qn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Qr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Zn?(L_(this,a),this.Yz(),this.player.pauseVideo(),c=g.Dc(H_(this,a.targetUrl)),c=g.Ac(c),g.jL(c,void 0,a.Wb)):(c=this.player.getVideoData().Mb,
c=(0,g.x)(this.rM,this,c,H_(this,a.targetUrl),a.Wb),c=(0,g.x)(this.Yz,this,c),L_(this,a,c))}}};
g.h.rM=function(a,b,c){var d=g.lq(b);a&&d&&(d.v||d.list)?g.LX(this.player.app,d.v,c,d.list,!1,void 0):g.iL(b,c)};
g.h.Zq=function(a,b){g.Qn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.X(this.player).g?(new g.M(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),K_(this,b.ND),J_(this,b.id,!0))};
g.h.Qr=function(a,b){g.Sn(a.element,"ytp-ce-element-hover");g.Sn(a.element,"ytp-ce-force-expand");J_(this,b.id,!1)};
g.h.Yz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var R1=[346,426,470,506,570,640,853,1280,1920],S1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),rpa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var hoa={UN:"current",bP:"new"};var joa={CLOSE:"close",fP:"openUrl",TB:"subscribe"},koa={PN:"click",CLOSE:"close",xO:"hidden",FP:"rollOut",PB:"rollOver",QB:"shown"};var moa={kQ:"xx",lQ:"xy",mQ:"yx",nQ:"yy"};g.t(f0,Z_);var roa={oB:"anchored",BP:"rect",IP:"shapeless"};var voa={CLOSED:"closed",oP:"playerControlShow",PB:"rollOver",QB:"shown"};j0.prototype.Ib=function(){var a=Doa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
j0.prototype.showLinkIcon=function(){return l0(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var k0={oB:"anchored",rB:"branding",CHANNEL:"channel",TN:"cta",zO:"highlightText",NO:"label",PLAYLIST:"playlist",rP:"popup",MP:"speech",TB:"subscribe",WP:"title",VIDEO:"video",gQ:"website"},zoa={rB:"branding",GN:"card",aO:"drawer",yO:"highlight",VO:"marker",wP:"promotion",TEXT:"text",iQ:"widget"},Aoa={eQ:"video_relative",pP:"player_relative"};s0.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Pb(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.M(this.u,a,d))};t0.prototype.ga=function(){return this.u};
t0.prototype.l=function(){};var x0={bevel:1,dropshadow:2};g.t(C0,t0);
C0.prototype.l=function(a,b){var c=p0(a);if(c){var d=c0(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=o0(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.qh(a0(b,b0(e,new g.nh(e.D,e.F,e.Wi,e.l),b.g))),k=d.clone();c=new g.nh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.g;k=A0(k,c.effects);l=u0(this,k.width,k.height);m=z0(c,k.width,k.height,this.g);
d=new g.nh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.ud(f.x-k.left,f.y-k.top);this.o=17*Y_(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.g;var p=this.g&&m0(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new h_(r,p?f.i:f.borderColor):null)?f.g/2:0;r=Loa(d,n);var u=this.A(d,e,n,r),z=n.x;n=n.y;var C=d.width,E=d.height,F=d.left;d=d.top;var L=new LZ;L.moveTo(F+e+p,d+p);"t"==r&&(L.Zb(u.start,d+p),L.Zb(z,n),L.Zb(u.end,d+p));L.Zb(F+C-e-p,d+p);MZ(L,e,e,-90);"r"==r&&(L.Zb(F+C-p,u.start),L.Zb(z,n),L.Zb(F+
C-p,u.end));L.Zb(F+C-p,d+E-e-p);MZ(L,e,e,0);"b"==r&&(L.Zb(u.end,d+E-p),L.Zb(z,n),L.Zb(u.start,d+E-p));L.Zb(F+e+p,d+E-p);MZ(L,e,e,90);"l"==r&&(L.Zb(F+p,u.end),L.Zb(z,n),L.Zb(F+p,u.start));L.Zb(F+p,d+e+p);MZ(L,e,e,180);L.close();z_(l,L,f,m);if(m=this.ga())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.Hh(m,k.left,k.top),g.Rh(m,k.width,k.height),B0(l,m,c.effects)}}}};
C0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.qd(k-f/2,l+b,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(D0,t0);D0.prototype.l=function(a,b){var c=p0(a);if(c){var d=c0(c,b);if(!(0>=d.width||0>=d.height)){var e=a.g;c=A0(d,e.effects);var f=u0(this,c.width,c.height),k=new h_(!e.l&&this.g?1:e.l,e.bgColor),l=new EZ("#000",0);d=y0(new g.nh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);z_(f,d,k,l);f=this.ga();g.J(f,"annotation-shape");e=e.g;nZ(f,this.g?Math.max(e,.9):e);g.Hh(f,c.left,c.top);g.Rh(f,c.width,c.height)}}};g.t(E0,t0);
E0.prototype.l=function(a,b){var c=p0(a);if(c){var d=c0(c,b);if(!(0>=d.width||0>=d.height)){c=a.g;var e=A0(d,c.effects),f=u0(this,e.width,e.height),k=new g.nh(0,0,d.width,d.height);d=z0(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.g;var n=this.g&&m0(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new h_(p,n?m.i:m.borderColor):null;k=y0(k,l,m?m.g/2+1:0);z_(f,k,m,d);if(k=this.ga())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.Hh(k,e.left,e.top),g.Rh(k,e.width,e.height),B0(f,k,c.effects)}}};g.t(F0,C0);F0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(G0,g.D);g.h=G0.prototype;g.h.qx=function(){this.F||(this.o&&g.Th(this.o,!0),this.u&&g.Th(this.u,!0),this.l&&(this.l.g=!0,nZ(this.i,L0(this)?1:0),this.l.l(this.g,I0(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.aa.Nm(g.QJ(this.A),"mouseleave",function(a){this.nn.stop();this.Ag(a)}))};
g.h.Ag=function(){this.F&&(this.N?this.D.start():this.tw(),this.l&&(this.l.g=!1,nZ(this.i,L0(this)?1:0),this.l.l(this.g,I0(this))),this.F=!1,this.H&&(this.aa.La(this.H),this.H=null))};
g.h.tw=function(){this.o&&g.Th(this.o,!1);this.u&&g.Th(this.u,!1)};
g.h.AF=function(a){this.ba=a;this.nn.Qj()};
g.h.pD=function(){var a=this.ba,b=new g.ud(a.clientX,a.clientY),c=g.Lh(this.A.getRootNode()),d=M0(c,this.P);c=(this.u&&oZ(this.u)||this.o&&oZ(this.o))&&M0(c,this.N);d&&d.contains(b)||c&&c.contains(b)?this.qx(a):this.Ag(a)};
g.h.show=function(){var a=this.g.g;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=I0(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new D0:"popup"==this.g.style?d=new E0:"anchored"==this.g.style?d=new C0:"speech"==this.g.style&&(d=new F0);d&&(d.l(this.g,c),this.l=d,c=d.ga())&&(g.Th(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Rd("DIV",c);g.Th(this.i,!1);this.g.l&&(this.C=g.Rd("DIV","inner-text"),"label"==this.g.style&&(g.J(this.C,"player-label-text"),this.C.style.backgroundColor=this.g.g.bgColor),g.be(this.C,this.g.l),this.i.appendChild(this.C));g.Ep(this.i,"annotation_id",this.g.id);this.R(this.i);Moa(this,this.i);if(m0(this.g)&&this.g.showLinkIcon()){if(d=this.g.Ib())c=this.i,d=new g.Mm(W_(d)),c.title=d.g+d.i;this.u=g.Rd("SPAN","annotation-link-icon");g.Th(this.u,
!1);this.i.appendChild(this.u)}Noa(this);m0(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=h0(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ga()&&(this.l.ga().style.zIndex=a)}g.Th(this.i,!0);nZ(this.i,L0(this)?1:0);K0(this);this.l&&this.l.ga()&&g.Th(this.l.ga(),!0)};
g.h.hide=function(){this.i&&g.Th(this.i,!1);this.l&&this.l.ga()&&g.Th(this.l.ga(),!1);this.I&&(this.aa.La(this.I),this.I=null)};g.t(N0,g.D);g.h=N0.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(O0(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.ox,this),this.i.subscribe("onVideoAreaChange",this.ez,this))};
g.h.destroy=function(){if(this.view){O0(this);var a=this.view,b=a.aa;g.Nr(b.g);b.g.length=0;a.nn.dispose();a.D.dispose();a.i&&g.Xd(a.i);a.l&&a.l.ga()&&g.Xd(a.l.ga())}P0(this)};
g.h.ez=function(){K0(this.view)};
g.h.ox=function(){K0(this.view)};Z0.prototype.l=function(a,b){var c=g.ge(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
Z0.prototype.u=function(a,b){var c=g.ge(b.target,null,"iv-card-poll",void 0);if(c)if(a.Pd)g.Hd("iv-card-sign-in-button",c).click();else{var d=parseInt(Nna(b.target),10);if(null==a.ge)a.choices[d].count++,a.ge=d;else if(a.ge!=d){var e=a.choices[a.ge];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.ge=d}else e=a.choices[a.ge],e.count=Math.max(e.count-1,0),a.ge=null;a1(a,c);g.Iq(this.g.videoData.Ed,{Dc:{action_poll_vote:1},ub:{poll_id:a.id,index:d,session_token:a.XM}});V0(this.g.logger,a.Ya,void 0,
{"link-id":d},a.pd.click,5);(c=g.$s())&&a.mf&&g.Ns(c,a.mf)}};g.t(n1,g.D);g.h=n1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.PD(a,b,{id:c});g.G(this,a);a.namespace="annotations_module";d&&jZ(a).subscribe("onEnter",d,this);e&&jZ(a).subscribe("onExit",e,this);g.XJ(this.context.Y,[a])};
g.h.Un=function(){this.context.i.subscribe("resize",this.Kl,this)};
g.h.ga=function(){return this.Ba};
g.h.Ki=function(a,b,c,d,e,f,k){this.context.g.ca(a,"click",g.Sa(this.Mm,b,c,d,e,f||[],k||0),this);this.context.g.ca(a,"touchstart",g.Sa(function(){this.jt=!1}),this);
this.context.g.ca(a,"touchmove",g.Sa(function(){this.jt=!0}),this)};
g.h.Mm=function(a,b,c,d,e,f,k){if(this.jt)return!1;k&&(k.stopPropagation(),k.preventDefault());Zoa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.H)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Xd(this.ga())};
g.h.Kl=function(){};g.t(q1,n1);g.h=q1.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Sh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Kl=function(){var a=this.isAvailable();g.Th(this.ga(),a);g.K(this.context.Y.getRootNode(),"ytp-iv-drawer-enabled",a);lZ(this.i)};
g.h.destroy=function(){this.i.Gi(!1);this.i.getRootNode().removeChild(this.A);g.Pp(this.I);g.Nr(this.ba);this.Z&&this.Z.dispose();this.C&&this.C.dispose();n1.prototype.destroy.call(this)};
g.h.YE=function(a){this.N.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.eA=function(a){if(!g.Qn(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.$s(),c=this.g?this.g.Fb.ce:this.H;b&&c&&CZ(b,[c]);this.g=a;s1(this)}oZ(this.ga())&&(2==this.context.Y.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Y.getAdState():void 0):(b=isNaN(void 0)?this.context.Y.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Y.getCurrentTime()),b&&a.Fb.teaserDurationMs&&this.i.Gi(!0,{teaserText:a.Fb.teaserText,durationMs:a.Fb.teaserDurationMs}));this.ka.isActive()||
((!this.u||!this.N.isActive()&&this.W)&&u1(this,a),this.ka.start(910+a.Fb.teaserDurationMs))}};
g.h.kM=function(a){this.u||(this.g=a,s1(this),u1(this,a),o1(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.pC=function(){if(this.u){X0(this.context.logger,this.R,4,v1(this).pd.close);var a=g.$s();a&&this.P&&g.Ns(a,this.P);p1(this)}};
g.h.zC=function(){g.K(this.A,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.iE=function(){var a=g.$s(),b=v1(this);b=b?b.ce:this.H;a&&b&&BZ(a,[b])};
g.h.hE=function(){var a=g.$s(),b=v1(this);b=b?b.ce:this.H;a&&b&&CZ(a,[b])};
g.h.lE=function(){var a=v1(this);Y0(this.context.logger,8,a.Ya,a.pd.yM);var b=g.$s();b&&a&&BZ(b,[a.Ye,a.ce])};
g.h.kE=function(){var a=g.$s(),b=v1(this);a&&b&&CZ(a,[b.Ye])};
g.h.jE=function(a){var b=v1(this),c=g.$s();this.g?a?(a=this.context.logger,Y0(a,9,b.Ya,b.pd.Ms),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.Ye&&g.Ns(c,b.Ye)):(a=this.context.logger,Y0(a,12,b.Ya,b.pd.Ms),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.ce&&g.Ns(c,b.ce)):(a=this.context.logger,X0(a,this.R,12,b.pd.Ms),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.Ns(c,this.H))};g.t(w1,n1);w1.prototype.Un=function(){n1.prototype.Un.call(this);gpa(this)};
w1.prototype.show=function(){n1.prototype.show.call(this);var a=g.$s(),b=this.annotation.data;a&&b&&(b=b.session_data)&&BZ(a,[g.Js(b.itct)])};
w1.prototype.hide=function(){n1.prototype.hide.call(this);var a=g.$s(),b=this.annotation.data;a&&b&&(b=b.session_data)&&CZ(a,[g.Js(b.itct)])};g.t(x1,w1);g.h=x1.prototype;g.h.sM=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Sh(a);this.g||(g.Qh(a,e.width),g.Qh(b,e.width));g.zh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.zh(c,"right","1px");this.o=!0;g.Th(a,!0);this.A=new g.M(function(){g.J(this.ga(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.LD=function(a,b){g.Sn(this.ga(),"iv-branding-active");this.C=new g.M((0,g.x)(function(){g.Th(a,!1);this.g||g.Qh(b,0)},this),250);
this.C.start();this.o=!1};
g.h.show=function(){if(!this.isActive){w1.prototype.show.call(this);if(!this.D){g.J(this.ga(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Rd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Th(this.i,!1);var b=g.Rd("DIV","branding-img-container",this.i);this.ga().appendChild(b);var c=g.Rd("DIV","iv-branding-context-name");g.be(c,a.channel_name);var d=g.Rd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.FV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Y),this.g.g(d);b=g.Rd("DIV","iv-branding-context-subscribe-caret");c=g.Rd("DIV","branding-context-container-inner",b,c,d);g.Th(c,!1);d=g.Rd("DIV","branding-context-container-outer",c);g.zh(d,"right",this.u+"px");this.ga().appendChild(d);var e=this.annotation.Ib();e&&this.Ki(this.i,e,this.annotation.id,a.session_data,
this.annotation.Ya);this.l=new g.M(g.Sa(this.LD,c,d),500,this);g.G(this,this.l);this.context.g.ca(this.ga(),"mouseover",(0,g.x)(this.sM,this,c,d,b,a.image_height));this.context.g.ca(this.ga(),"mouseout",(0,g.x)(this.l.start,this.l,void 0));this.D=!0}U0(this.context.logger,this.annotation.Ya);g.Th(this.ga(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=mZ(a).width;c=g.Ha(void 0)?void 0:b;g.Hh(a,c);f=new zZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Pna);g.G(this,f);this.context.l.ca(f,
"begin",g.Sa(g.Th,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(w1.prototype.hide.call(this),g.Th(this.ga(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);w1.prototype.destroy.call(this)};g.t(y1,w1);g.h=y1.prototype;g.h.show=function(){this.isActive||(w1.prototype.show.call(this),this.H||(hpa(this),this.H=!0),g.Th(this.ga(),!0),this.annotation&&this.annotation.Ya&&U0(this.context.logger,this.annotation.Ya),g.Gg(function(){g.Sn(this.ga(),"iv-promo-inactive")},100,this),this.ga().removeAttribute("aria-hidden"),this.isActive=!0,B1(this),A1(this),C1(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.ga(),"iv-promo-inactive"),this.isActive=!1,this.ga().setAttribute("aria-hidden",!0))};
g.h.Mm=function(a,b,c,d,e,f,k){return this.u?!1:w1.prototype.Mm.call(this,a,b,c,d,e,f,k)};
g.h.hq=function(a,b){b.stopPropagation();A1(this);C1(this,a);this.g.focus()};
g.h.rD=function(a){this.F=!0;this.hq(500,a)};
g.h.qD=function(){this.F=!1;z1(this)};
g.h.iD=function(a){a.stopPropagation();this.hide();W0(this.context.logger,this.annotation.Ya)};
g.h.jD=function(a){a.stopPropagation();B1(this);this.u=!0;g.J(this.ga(),"iv-promo-collapsed-no-delay");this.A.start();W0(this.context.logger,this.annotation.Ya)};
g.h.destroy=function(){this.A.dispose();w1.prototype.destroy.call(this)};g.t(D1,g.rK);g.h=D1.prototype;g.h.wc=function(a,b){if(!E1(g.X(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Un(b);c&&J1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(t1(this.g,b),lZ(this.player)),!0}return null};
g.h.getOptions=function(){return E1(g.X(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.un=function(){if(this.o){var a=g.QJ(this.player).getVideoContentRect(!0);g.Rh(this.o.element,a.width,a.height);g.Hh(this.o.element,a.left,a.top)}if(this.g){var b=g.VJ(this.player);a=this.g;b=b.width;g.K(a.A,"iv-drawer-small",426>=b);g.K(a.A,"iv-drawer-big",1280<=b)}};
g.h.XJ=function(a){this.fc(a.state);g.U(a.state,2)&&(this.ud()&&this.Ce()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Gi(!1))};
g.h.load=function(){g.rK.prototype.load.call(this);this.fc(g.PJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.LI,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.bq()&&(c=K1(this,c));c={format:"XML",Xc:c,onError:d,Dc:{}};a.isPharma&&(c.Dc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.X(this.player);"gaming"==d.playerStyle&&(c.Dc.gaming="1");(b=d.I.get(b))&&L1(c,b);b=b&&(b.Ql||b.Pl);if(!a.Dl||b)a.Ed?F1(this,a.Ed,c):(this.l=(0,g.x)(this.HE,this,c),this.player.addEventListener("videodatachange",this.l));g.dK(this.player,this.o.element,4);this.un();(a=a.Qa&&a.Qa.cards&&a.Qa.cards.cardCollectionRenderer||null)&&opa(this,a)};
g.h.fc=function(a){a=!a.isCued()&&!g.U(a,1024);g.JC(this.u,a);g.JC(this.o,a)};
g.h.HE=function(a){var b=this.player.getVideoData();b.Ed&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),F1(this,b.Ed,a))};
g.h.unload=function(){Roa(this.D);g.$J(this.player,"annotations_module");g.Lb(this.i,function(a){a.destroy()});
g.Lb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,lZ(this.player));this.I=!1;this.C&&(this.C.abort(),this.C=null);this.i={};this.P={};this.u.hide();g.rK.prototype.unload.call(this);g.IC(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.LI=function(a,b,c){this.C=null;if(!H1(this,b,a)&&(a=g.yq(c)&&c.responseXML?c.responseXML:null)){J1(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.l,f.visible=!0);b=new g.PD(c,e,f);a.push(b)}}g.XJ(this.player,a)}};
g.h.dz=function(a){a==this.player.getVideoData().videoId&&(this.loaded?mpa(this):this.load())};
g.h.EE=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,N1(this,a),U0(this.D,b.Ya))};
g.h.FE=function(a){O1(this,a.getId())};
g.h.rw=function(a){a&&(a.hide(),Q1(this,"shown",!1,a.annotation.id),this.Yl(a.annotation,"hidden"))};
g.h.pA=function(a){a&&(a.show(),Q1(this,"shown",!0,a.annotation.id),this.Yl(a.annotation,"shown"))};
g.h.lL=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;n0(d.annotation,function(f){e=e||f.value});
ppa(this,a,b,e)}};
g.h.QH=function(a){if(a&&a.id){var b=a.Ib();if(b){var c=W_(b);if(c){var d=(0,g.x)(this.Yl,this,a,"click");if("new"==m1(c,b.target)||P1(this,b))d(),d=null;V0(this.D,a.Ya,d)}}}};
g.h.Yl=function(a,b){Coa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!P1(this,c.url))){e=l1(c.url);var f=Woa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=I1(this).Y,g.LX(d.app,e,void 0,void 0,void 0,void 0),f&&I1(this).Y.ac()&&I1(this).Y.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.X(this.player),(d=W_(c.url))?(f=j1(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Sa(Xoa,e.pageId,e.gc),d=new g.Mm(d),e=e(d.i),d.i=e,d=d.toString())):d=null,d&&
(this.player.pauseVideo(),c=m1(d,c.url.target),e=a.itct,"ei"in g.lq(d)&&(d=g.hh(d,"ei")),g.jL(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.UI=function(){Q1(this,"playerControlShow",!1)};
g.h.NK=function(){Q1(this,"playerControlShow",!0)};
g.h.GE=function(a){Q1(this,"rollOver",!0,a.id)};
g.h.Ag=function(a){Q1(this,"rollOver",!1,a.id)};
g.h.tI=function(a){a&&a.id&&(this.i[a.id].l=!0,O1(this,a.id),W0(this.D,a.Ya),this.Yl(a,"close"),Q1(this,"closed",!0,a.id))};
g.h.ud=function(){return!!this.g&&this.g.isAvailable()};
g.h.Ce=function(){this.ud();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ud();this.g&&(a?c?o1(this.g,c,b):o1(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):p1(this.g))};
g.h.Gi=function(a,b){this.player.M(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.X(this.player).I.unsubscribe("vast_info_card_add",this.dz,this);g.Sn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.N,b=0,c=a.length;b<c;b++)g.cq(a[b]);this.N.length=0;g.rK.prototype.T.call(this)};g.NU.annotations_module=D1;g.NU.creatorendscreen=C_;})(_yt_player);
