(function(g){var window=this;var x3=function(a,b,c){var d=b.oa();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.xc(c?c:"mqdefault.jpg");var f=b instanceof g.TA&&b.lengthSeconds?g.wQ(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.TD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.TA?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.ij||g.bN("\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c $TITLE",
{TITLE:b.title}),duration:f,url:b.Nj(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.VD&&(d.playlist_length=b.getLength());a.update(d)},y3=function(a,b){g.KC.call(this,{B:"div",
V:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},z3=function(a){g.W.call(this,{B:"div",
V:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",J:[{B:"span",G:"ytp-upnext-header",U:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{B:"span",G:"ytp-upnext-title",U:"{{title}}"},{B:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
J:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{B:"circle",G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",
J:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",U:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({B:"button",V:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
U:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.G(this,this.A);this.A.ca("click",this.fI,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.u=null;this.F=new g.M(this.Sl,5E3,this);g.G(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.SJ);this.wy();this.K(a,"autonavvisibility",this.wy);this.K(a,"mdxnowautoplaying",this.kJ);this.K(a,"mdxautoplaycanceled",this.lJ);this.K(a,"mdxautoplayupnext",this.TA);3==this.l.getPresentingPlayerType()&&
(a=(a=g.RJ(g.LJ(this.l)))?a.ZC():null)&&this.TA(a)},A3=function(a,b){if(!a.o){g.Rp("a11y-announce","\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 "+a.u.title);
a.H=g.O();a.o=new g.M((0,g.x)(a.Uo,a,b),25);a.Uo(b);var c=b||g.R(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.la("onAutonavCoundownStarted",c)}g.Sn(a.element,"ytp-upnext-autoplay-paused")},C3=function(a){B3(a);
a.H=g.O();a.Uo();g.J(a.element,"ytp-upnext-autoplay-paused")},B3=function(a){a.o&&(a.o.dispose(),a.o=null)},D3=function(a,b){b=void 0===b?!1:b;
if(g.Q(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.oa(),a.Sl(),a.C=new Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:c.title,icon:c.xc()}),a.D=a.K(a.C,"click",a.KJ),a.F.start())}B3(a);a.l.nextVideo(!1,b)},E3=function(a){y3.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({B:"div",G:"ytp-subscribe-card",J:[{B:"img",G:"ytp-author-image",L:{src:b.Nd}},{B:"div",G:"ytp-subscribe-card-right",J:[{B:"div",G:"ytp-author-name",U:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.G(this,this.l);this.l.g(this.element);this.o=new g.FV("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f",null,"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",null,!0,!1,b.Qf,b.subscribed,
"trailer-endscreen",null,null,a);g.G(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},F3=function(a){var b=g.X(a),c=g.Nw||g.Ch?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{B:"a",V:e,L:{href:"{{url}}",target:d?b.u:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",J:[{B:"span",G:"ytp-videowall-still-info-bg",J:[{B:"span",G:"ytp-videowall-still-info-content",L:c,J:[{B:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",U:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{B:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{B:"span",V:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{B:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{B:"span",U:"{{playlist_length}}"},")"]}]},{B:"span",V:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],J:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{B:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.us(this);g.G(this,this.u);this.ca("click",this.D);this.ca("keypress",this.F);this.u.K(a,"videodatachange",this.C);g.X(a).F&&g.QN(a.app.R,this.element,this);this.C()},G3=function(a){g.gK(a.l,a.element);
var b=a.o.oa().videoId,c=a.o.getPlaylistId();g.LX(a.l.app,b,a.o.Wb,c,void 0,void 0)},H3=function(a){y3.call(this,a,"videowall-endscreen");
this.H=a;this.C=0;this.o=[];this.D=this.u=this.A=null;this.F=this.R=!1;this.O=null;this.aa=new g.us(this);g.G(this,this.aa);this.I=new g.M(g.Sa(g.J,this.element,"ytp-show-tiles"),0);g.G(this,this.I);var b=new g.W({B:"button",V:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},J:[g.fP()]});g.G(this,b);b.g(this.element);b.ca("click",this.yF,this);this.N=new g.FC({B:"div",G:"ytp-endscreen-content"});g.G(this,this.N);this.N.g(this.element);b=new g.W({B:"button",
V:["ytp-button","ytp-endscreen-next"],L:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},J:[g.gP()]});g.G(this,b);b.g(this.element);b.ca("click",this.xF,this);this.l=new z3(a);g.G(this,this.l);g.dK(this.player,this.l.element,4);this.hide()},I3=function(a){return g.eK(a.player)&&a.xu()&&!a.D},J3=function(a,b){return(0,g.B)(b.suggestions,function(c){c=g.KR(g.X(a.H),c);
g.G(a,c);return c})},K3=function(a){var b=a.Le();
b!=a.R&&(a.R=b,a.player.M("autonavvisibility"))},M3=function(a){g.rK.call(this,a);
this.g=null;this.i=new g.us(this);g.G(this,this.i);this.l=g.X(a);L3(a)?this.g=new H3(this.player):this.l.Ea?this.g=new E3(this.player):this.g=new y3(this.player);g.G(this,this.g);g.dK(this.player,this.g.element,4);this.Rz();this.i.K(a,"videodatachange",this.Rz,this);this.i.K(a,g.SD("endscreen"),this.KE,this);this.i.K(a,"crx_endscreen",this.LE,this)},L3=function(a){a=g.X(a);
return a.Ba&&!a.Ea};
g.t(y3,g.KC);y3.prototype.create=function(){this.created=!0};
y3.prototype.destroy=function(){this.created=!1};
y3.prototype.xu=function(){return!1};
y3.prototype.Le=function(){return!1};g.t(z3,g.W);g.h=z3.prototype;g.h.Sl=function(){this.C&&(this.F.stop(),this.La(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.wy=function(){g.JC(this,this.l.Le())};
g.h.KJ=function(){window.focus();this.Sl()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Uo=function(a){a=a||g.R(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.O()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?D3(this,!0):this.o&&this.o.start()};
g.h.SJ=function(a){!g.ae(this.A.element,g.Or(a))&&g.NR(a,this.l)&&D3(this)};
g.h.fI=function(){g.NJ(this.l,!0)};
g.h.kJ=function(a){this.l.getPresentingPlayerType();this.show();A3(this,a)};
g.h.TA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.oa().videoId==a.oa().videoId||(this.u=a,x3(this,a,"hqdefault.jpg"))};
g.h.lJ=function(){this.l.getPresentingPlayerType();B3(this);this.hide()};
g.h.T=function(){B3(this);this.Sl();g.W.prototype.T.call(this)};g.t(E3,y3);g.t(F3,g.W);F3.prototype.D=function(a){g.NR(a,this.l,this.A,this.o.Wb||void 0)&&G3(this)};
F3.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.Tr(a)||(G3(this),g.Sr(a))}};
F3.prototype.C=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Mb?!1:b.i};g.t(H3,y3);g.h=H3.prototype;g.h.create=function(){y3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=J3(this,a),this.u=a);this.If();this.aa.K(this.player,"appresize",this.If);this.aa.K(this.player,"onVideoAreaChange",this.If);this.aa.K(this.player,"videodatachange",this.zF);this.aa.K(this.player,"autonavchange",this.ir);this.aa.K(this.player,"autonavcancel",this.wF);a=this.u.autonavState;a!=this.O&&this.ir(a);this.aa.K(this.element,"transitionend",this.hL)};
g.h.destroy=function(){g.ws(this.aa);g.rf(this.o);this.o=[];this.A=null;y3.prototype.destroy.call(this);g.Sn(this.element,"ytp-show-tiles");this.I.stop();this.O=this.u.autonavState};
g.h.xu=function(){return 1!=this.u.autonavState};
g.h.show=function(){y3.prototype.show.call(this);g.Sn(this.element,"ytp-show-tiles");g.X(this.player).g?g.bo(this.I):this.I.start();(this.F||this.D&&this.D!=this.u.clientPlaybackNonce)&&g.NJ(this.player,!1);I3(this)?(K3(this),2==this.u.autonavState?g.Q(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?D3(this.l,!0):A3(this.l):3==this.u.autonavState&&C3(this.l)):(g.NJ(this.player,!0),K3(this))};
g.h.hide=function(){y3.prototype.hide.call(this);C3(this.l);K3(this)};
g.h.hL=function(a){g.Or(a)==this.element&&this.If()};
g.h.If=function(){if(this.A&&this.A.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.VJ(this.H,!0),b=g.ZC(this.H);b&&(b=b.zc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,u=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=r*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.qd(a.width/m||1,1,1.21);n*=g.qd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Rh(a,m,n);g.zh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.u=f;x3(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",I3(this));K3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.rd(p+this.C,l),0!=r){u=this.o[c];u||(u=new F3(this.player),this.o[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),E=Math.floor(n*(k+r)/e)-z-4,F=Math.floor(m*(f+r)/b)-C-4;g.Hh(u.element,C,z);g.Rh(u.element,F,E);g.zh(u.element,"transitionDelay",(k+f)/20+"s");g.K(u.element,"ytp-videowall-still-mini",1==r);g.K(u.element,"ytp-videowall-still-large",2<r);r=u;p=this.A[p];r.o!=p&&(r.o=p,x3(r,p,g.Qn(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Wb)&&p.itct)&&(u=r.l,g.X(u).F&&g.RN(u.app.R,r.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Xd(e.element),g.qf(e);this.o.length=c}};
g.h.zF=function(){var a=this.player.getVideoData();this.u!=a&&(this.C=0,this.A=J3(this,a),this.u=a,this.If())};
g.h.xF=function(){this.C+=this.o.length;this.If()};
g.h.yF=function(){this.C-=this.o.length;this.If()};
g.h.ZD=function(){return!!this.l.o};
g.h.ir=function(a){1==a?(this.F=!1,this.D=this.u.clientPlaybackNonce,B3(this.l),this.Da()&&this.If()):(this.F=!0,this.Da()&&I3(this)&&(2==a?A3(this.l):3==a&&C3(this.l)))};
g.h.wF=function(a){if(a){for(a=0;a<this.o.length;a++)g.hK(this.H,this.o[a].element,!0);this.ir(1)}else this.D=null,this.F=!1;this.If()};
g.h.Le=function(){return this.Da()&&I3(this)};g.t(M3,g.rK);g.h=M3.prototype;g.h.Sk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!L3(this.player)||b;a=a.Kc||g.Gy(a.Na);var c=g.lX(this.player.app);return b&&!a&&!c};
g.h.Le=function(){return this.g.Le()};
g.h.UD=function(){return this.Le()?this.g.ZD():!1};
g.h.T=function(){g.$J(this.player,"endscreen");g.rK.prototype.T.call(this)};
g.h.load=function(){g.rK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.rK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.KE=function(a){this.Sk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.LE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Rz=function(){g.$J(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.PD(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.G(this,a);var b=new g.PD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.G(this,b);g.XJ(this.player,[a,b])};g.NU.endscreen=M3;})(_yt_player);
