(function(g){var window=this;var Wpa=function(a,b){return g.Vb(a,b)},U4=function(){},Xpa=function(a){if(a.yc&&"function"==typeof a.yc)return a.yc();
if(g.Fa(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Ypa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.Fa(a))(0,g.A)(a,b,void 0);else{if(a.Gd&&"function"==typeof a.Gd)var c=a.Gd();else if(a.yc&&"function"==typeof a.yc)c=void 0;else if(g.Na(a)||g.Fa(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Xpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},V4=function(a){g.Um(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},W4=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.Zm(a.l,b,c)},X4=function(a){return(a=g.so(a))?new ActiveXObject(a):new XMLHttpRequest},Y4=function(a,b){return b+" ["+a.ba+" "+a.D+" "+a.getStatus()+"]"},Zpa=function(a){return"content-type"==a.toLowerCase()},Z4=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},$pa=function(a){return g.Md&&g.od(9)&&g.Ha(a.timeout)&&g.Ea(a.ontimeout)},$4=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},a5=function(a,b){if(a.g){Z4(a);
var c=a.g,d=a.P[0]?g.Ja:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},b5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;$4(a);a5(a)},c5=function(a){return a.g?a.g.readyState:0},d5=function(a){if(a.i&&"undefined"!=typeof g.aY)if(a.P[1]&&4==c5(a)&&2==a.getStatus())Y4(a,"Local request error detected and ignored");
else if(a.C&&4==c5(a))g.Gg(a.gw,0,a);else if(a.dispatchEvent("readystatechange"),4==c5(a)){Y4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!aqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<c5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";$4(a)}}finally{a5(a)}}},e5=function(a){g.Sf.call(this);
this.headers=new g.Jm;this.N=a||null;this.i=!1;this.P=this.g=null;this.ba=this.D="";this.u=0;this.l="";this.o=this.W=this.C=this.O=!1;this.A=0;this.F=null;this.Z="";this.I=this.R=!1},f5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},bqa=function(a,b){var c=[];
g.Lk(b,function(d){try{var e=g.Ho.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Go(e)&&c.push(d):c.push(d)},a);
return c},cqa=function(a,b){var c=bqa(a,b);
(0,g.A)(c,function(d){g.Ho.prototype.remove.call(this,d)},a)},g5=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},dqa=function(a,b){g.ab(a,b)||a.push(b)},h5=function(a){var b=0,c;
for(c in a)b++;return b},i5=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},eqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},fqa=function(a,b,c,d){var e=new g.Mm(null,void 0);
a&&g.Nm(e,a);b&&g.Om(e,b);c&&g.Pm(e,c);d&&(e.i=d);return e},j5=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return eqa(a)},k5=function(){this.g=[];
this.i=[]},l5=function(a,b){g.Mp[a]=!0;
var c=g.Kp();c&&c.publish.apply(c,arguments);g.Mp[a]=!1},m5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Jm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",gqa(this,a.capabilities||""),hqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},gqa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Sa(Wpa,iqa)).forEach(function(c){a.capabilities.add(c)})},hqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},n5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},o5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},p5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},jqa=function(a){return new n5(a)},q5=function(a){return g.Ma(a)?(0,g.B)(a,jqa):[]},r5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},s5=function(a){return g.Ma(a)?"["+(0,g.B)(a,r5).join(",")+"]":"null"},t5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},kqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},u5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},v5=function(a,b){return g.Ya(a,function(c){return o5(c,b)})},w5=function(a){try{var b=(0,g.dt)(),c=(0,g.ct)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},lqa=function(){var a=(0,g.ct)();
a&&cqa(a,a.g.jf(!0))},x5=function(){var a=g.ft("yt-remote-connected-devices")||[];
g.rb(a);return a},mqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},y5=function(a){g.et("yt-remote-connected-devices",a,86400)},A5=function(){if(z5)return z5;
var a=g.ft("yt-remote-device-id");a||(a=t5(),g.et("yt-remote-device-id",a,31536E3));for(var b=x5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return z5=d},B5=function(){var a=x5(),b=A5();
g.ab(a,b);g.gt()&&g.tb(a,b);a=mqa(a);if(0==a.length)try{g.gs("remote_sid")}catch(c){}else try{g.fs("remote_sid",a.join(","),-1)}catch(c){}},C5=function(){return g.ft("yt-remote-session-browser-channel")},D5=function(){return g.ft("yt-remote-local-screens")||[]},E5=function(){g.et("yt-remote-lounge-token-expiration",!0,86400)},nqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(D5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.jj)(c,function(d){return!g.ab(b,d)})&&E5();
g.et("yt-remote-local-screens",a,31536E3)},oqa=function(a,b){g.et("yt-remote-session-browser-channel",a);
g.et("yt-remote-session-screen-id",b);var c=x5(),d=A5();g.ab(c,d)||c.push(d);y5(c);B5()},F5=function(a){a||(w5("yt-remote-session-screen-id"),w5("yt-remote-session-video-id"));
B5();a=x5();g.eb(a,A5());y5(a)},H5=function(){if(!G5){var a=g.Ro();
a&&(G5=new g.Bo(a))}return G5?!!G5.get("yt-remote-use-staging-server"):!1},I5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},J5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},L5=function(a){a.length?K5(a.shift(),function(){L5(a)}):M5()},pqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},K5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},M5=function(){var a=J5();
a&&a(!1,"No cast extension found")},N5=function(){if(qqa){var a=2,b=J5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;K5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",M5,c)}},rqa=function(){N5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);L5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},O5=function(a,b,c){g.D.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Uc=b;this.u=(0,g.x)(this.eD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},P5=function(){},Q5=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.aa=new g.$m(this);this.i=new g.Fg;this.i.setInterval(250)},S5=function(a,b,c){a.Wh=1;
a.Vf=V4(b.clone());a.rh=c;a.u=!0;R5(a,null)},T5=function(a,b,c,d,e){a.Wh=1;
a.Vf=V4(b.clone());a.rh=null;a.u=c;e&&(a.Xz=!1);R5(a,d)},R5=function(a,b){a.Ei=(0,g.H)();
U5(a);a.Dg=a.Vf.clone();W4(a.Dg,"t",a.A);a.il=0;a.sc=a.g.zp(a.g.Uk()?b:null);0<a.eq&&(a.Gn=new g.zl((0,g.x)(a.eB,a,a.sc),a.eq));a.aa.ca(a.sc,"readystatechange",a.UL);var c=a.Zg?g.cc(a.Zg):{};a.rh?(a.no="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.sc.send(a.Dg,a.no,a.rh,c)):(a.no="GET",a.Xz&&!g.Od&&(c.Connection="close"),a.sc.send(a.Dg,a.no,null,c));a.g.se(1)},a6=function(a,b,c){for(var d=!0;!a.Pg&&a.il<c.length;){var e=sqa(a,c);
if(e==V5){4==b&&(a.ng=4,W5(15),d=!1);break}else if(e==X5){a.ng=4;W5(16);d=!1;break}else Y5(a,e)}4==b&&0==c.length&&(a.ng=1,W5(17),d=!1);a.we=a.we&&d;d||(Z5(a),$5(a))},sqa=function(a,b){var c=a.il,d=b.indexOf("\n",c);
if(-1==d)return V5;c=Number(b.substring(c,d));if(isNaN(c))return X5;d+=1;if(d+c>b.length)return V5;var e=b.substr(d,c);a.il=d+c;return e},d6=function(a,b){a.Ei=(0,g.H)();
U5(a);var c=b?window.location.hostname:"";a.Dg=a.Vf.clone();g.Um(a.Dg,"DOMAIN",c);g.Um(a.Dg,"t",a.A);try{a.Ae=new ActiveXObject("htmlfile")}catch(n){Z5(a);a.ng=7;W5(22);$5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in b6)k=b6[l];else if(l in c6)k=b6[l]=c6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
b6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.rc("b/12014412"),d+"</body></html>");a.Ae.open();a.Ae.write(g.Nc(c));a.Ae.close();a.Ae.parentWindow.m=(0,g.x)(a.kL,a);a.Ae.parentWindow.d=(0,g.x)(a.cz,a,!0);a.Ae.parentWindow.rpcClose=(0,g.x)(a.cz,a,!1);c=a.Ae.createElement("DIV");a.Ae.parentWindow.document.body.appendChild(c);d=g.Dc(a.Dg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.se(1)},U5=function(a){a.kt=(0,g.H)()+a.o;
e6(a,a.o)},e6=function(a,b){if(null!=a.Xi)throw Error("WatchDog timer not null");
a.Xi=f6((0,g.x)(a.uL,a),b)},g6=function(a){a.Xi&&(g.v.clearTimeout(a.Xi),a.Xi=null)},$5=function(a){a.g.dw()||a.Pg||a.g.tn(a)},Z5=function(a){g6(a);
g.qf(a.Gn);a.Gn=null;a.i.stop();g.bn(a.aa);if(a.sc){var b=a.sc;a.sc=null;b.abort();b.dispose()}a.Ae&&(a.Ae=null)},Y5=function(a,b){try{a.g.Wy(a,b),a.g.se(4)}catch(c){}},i6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;h6(a,b,function(k){k?c(!0):g.v.setTimeout(function(){i6(a,b,c,d,f)},f)})}},h6=function(a,b,c){var d=new Image;
d.onload=function(){try{j6(d),c(!0)}catch(e){}};
d.onerror=function(){try{j6(d),c(!1)}catch(e){}};
d.onabort=function(){try{j6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{j6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
i5(d,a)},j6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},k6=function(a){this.g=a;
this.i=new P5},m6=function(a){var b=l6(a.g,a.kj,"/mail/images/cleardot.gif");
V4(b);i6(b.toString(),5E3,(0,g.x)(a.lC,a),3,2E3);a.se(1)},o6=function(a){var b=a.g.F;
if(null!=b)W5(5),b?(W5(11),n6(a.g,a,!1)):(W5(12),n6(a.g,a,!0));else if(a.Cd=new Q5(a,void 0,void 0,void 0),a.Cd.Zg=a.bq,b=a.g,b=l6(b,b.Uk()?a.Tj:null,a.cq),W5(5),!g.Md||g.pd(10))W4(b,"TYPE","xmlhttp"),T5(a.Cd,b,!1,a.Tj,!1);else{W4(b,"TYPE","html");var c=a.Cd;a=!!a.Tj;c.Wh=3;c.Vf=V4(b.clone());d6(c,a)}},p6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new P5;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},tqa=function(a,b){this.g=a;
this.map=b;this.context=null},q6=function(a){g.sf.call(this,"statevent",a)},r6=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},s6=function(a){g.sf.call(this,"serverreachability",a)},w6=function(a){t6(a);
if(3==a.g){var b=a.Ck++,c=a.gm.clone();g.Um(c,"SID",a.l);g.Um(c,"RID",b);g.Um(c,"TYPE","terminate");u6(a,c);b=new Q5(a,a.l,b,void 0);b.Wh=2;b.Vf=V4(c.clone());i5(new Image,b.Vf.toString());b.Ei=(0,g.H)();U5(b)}v6(a)},y6=function(a){a.DC(1,0);
a.gm=l6(a,null,a.Zp);x6(a)},t6=function(a){a.dg&&(a.dg.abort(),a.dg=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.lf&&(g.v.clearTimeout(a.lf),a.lf=null);z6(a);a.yd&&(a.yd.cancel(),a.yd=null);a.jg&&(g.v.clearTimeout(a.jg),a.jg=null)},A6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new tqa(a.zH++,b));2!=a.g&&3!=a.g||x6(a)},x6=function(a){a.yd||a.jg||(a.jg=f6((0,g.x)(a.bz,a),0),a.Qh=0)},D6=function(a,b){if(1==a.g){if(!b){a.Ck=Math.floor(1E5*Math.random());
var c=a.Ck++,d=new Q5(a,"",c,void 0);d.Zg=null;var e=B6(a),f=a.gm.clone();g.Um(f,"RID",c);g.Um(f,"CVER","1");u6(a,f);S5(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?C6(a,b):0==a.i.length||a.yd||C6(a))},C6=function(a,b){if(b)if(6<a.Qg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Ck-1;var d=B6(a)}else c=b.C,d=b.rh;else c=a.Ck++,d=B6(a);var e=a.gm.clone();g.Um(e,"SID",a.l);g.Um(e,"RID",c);g.Um(e,"AID",a.ji);u6(a,e);c=new Q5(a,a.l,c,a.Qh+1);c.Zg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;S5(c,e,d)},u6=function(a,b){if(a.Rc){var c=a.Rc.Gv();
c&&g.Lb(c,function(d,e){g.Um(b,e,d)})}},B6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Qg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Qg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},E6=function(a){a.Rb||a.lf||(a.C=1,a.lf=f6((0,g.x)(a.az,a),0),a.Ih=0)},G6=function(a){if(a.Rb||a.lf||3<=a.Ih)return!1;
a.C++;a.lf=f6((0,g.x)(a.az,a),F6(a,a.Ih));a.Ih++;return!0},n6=function(a,b,c){a.ko=c;
a.Ie=b.xf;a.A||y6(a)},z6=function(a){null!=a.Ug&&(g.v.clearTimeout(a.Ug),a.Ug=null)},F6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},I6=function(a,b){if(2==b||9==b){var c=null;
a.Rc&&(c=null);var d=(0,g.x)(a.zM,a);c||(c=new g.Mm("//www.google.com/images/cleardot.gif"),V4(c));h6(c.toString(),1E4,d)}else W5(2);H6(a,b)},H6=function(a,b){a.g=0;
a.Rc&&a.Rc.Iu(b);v6(a);t6(a)},v6=function(a){a.g=0;
a.Ie=-1;if(a.Rc)if(0==a.o.length&&0==a.i.length)a.Rc.lp();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Rc.lp(b)}},l6=function(a,b,c){var d=g.Vm(c);
if(""!=d.g)b&&g.Om(d,b+"."+d.g),g.Pm(d,d.u);else{var e=window.location;d=fqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.xj&&g.Lb(a.xj,function(f,k){g.Um(d,k,f)});
g.Um(d,"VER",a.Qg);u6(a,d);return d},f6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},W5=function(a){J6.dispatchEvent(new q6(J6,a))},K6=function(){},uqa=function(a,b){this.action=a;
this.params=b||{}},L6=function(a,b){g.D.call(this);
this.g=new g.M(this.cL,0,this);g.G(this,this.g);this.Uc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},M6=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Ao;this.i=new L6(this.dM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},vqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.ko,sessionId:a.g.l,arrayId:a.g.ji}},N6=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&D6(a.g),w6(a.g));a.D=0},O6=function(a){return!!a.g&&3==a.g.g},wqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},P6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},Q6=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.ch(c+b,{})},R6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.o,d,!0),onError:g.Sa(a.l,e),he:g.Sa(a.u,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Eq(b,a)},xqa=function(){var a=S6;
T6();U6.push(a);V6(U6)},W6=function(a,b){T6();
var c=U6,d=yqa(a,String(b));0==c.length?zqa(d):(V6(c),(0,g.A)(c,function(e){e(d)}))},T6=function(){U6||(U6=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",U6,void 0))},zqa=function(a){var b=(X6+1)%50;
X6=b;Y6[b]=a;Z6||(Z6=49==b)},V6=function(a){var b=Y6;
if(b[0]){var c=X6,d=Z6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.A)(a,function(f){f(e)})}while(d!=c);
Y6=Array(50);X6=-1;Z6=!1}},yqa=function(a,b){var c=((0,g.H)()-Aqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},$6=function(a){g.P.call(this);
this.C=a;this.g=[]},a7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Bqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!u5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=a7(a,b[d])||c;return c},Cqa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},b7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},d7=function(a){$6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;c7(this);this.info("Initializing with "+s5(this.g))},e7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=Q6(a.l,"/pairing/get_lounge_token_batch");
R6(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.oD,a),(0,g.x)(a.nD,a))}},c7=function(a){var b=q5(D5());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Bqa(a,b)},f7=function(a,b){nqa((0,g.B)(a.g,p5));
b&&E5()},h7=function(a,b){g.P.call(this);
this.A=b;var c=g.ft("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;g7("Initialized with "+g.Kg(this.g))},i7=function(a,b,c){var d=Q6(a.u,"/pairing/get_screen_availability");
R6(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},j7=function(a,b){a:if(h5(b)!=h5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(g7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.M("screenChange"));Dqa(a)},k7=function(a){isNaN(a.l)||g.Jp(a.l);
a.l=g.Hp((0,g.x)(a.ls,a),0<a.o&&a.o<(0,g.H)()?2E4:1E4)},g7=function(a){W6("OnlineScreenService",a)},l7=function(a){var b={};
(0,g.A)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},Dqa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.et("yt-remote-online-screen-ids",a.join(","),60):w5("yt-remote-online-screen-ids")},m7=function(a){$6.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Eqa(this)},o7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Id();if(k=(c?v5(k,c):null)||v5(k,b)){k.uuid=b;var l=n7(a,k);i7(a.i,l,function(m){e(m?l:null)})}else c?Fqa(a,c,(0,g.x)(function(m){var n=n7(this,new n5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));i7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},p7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Fqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Eq(Q6(a.A,"/pairing/get_lounge_token_batch"),e)},q7=function(a){a.g=a.l.Id();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+s5(a.g))},Eqa=function(a){r7(a);
a.l=new d7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.wD,a));q7(a);a.o=q5(g.ft("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+s5(a.o));a.i=new h7(a.A,(0,g.x)(a.Id,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.M("onlineScreenChange")},a))},n7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=v5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.et("yt-remote-automatic-screen-cache",(0,g.B)(a.o,p5)));r7(a);a.u[b.uuid]=b.id;g.et("yt-remote-device-id-map",a.u,31536E3);return b},r7=function(a){a.u=g.ft("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.P.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},t7=function(a,b){W6(a.P,b)},v7=function(a,b){s7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.eN,this);this.u=(0,g.x)(this.FL,this);this.o=g.Hp((0,g.x)(function(){u7(this,null)},this),12E4)},Gqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Kg(b))},u7=function(a,b){g.Jp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.vn,a),d=(0,g.x)(a.Ld,a);a.Wv(b,c,d,5)}}else a.Ld(Error("Waiting for session status timed out."))},w7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.N=c;this.u=null;this.C=g.Ja;this.A=NaN;this.I=(0,g.x)(this.hN,this);this.g=g.Ja},x7=function(a){a.g=a.F.jB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ja;
this.vn(b)},a),(0,g.x)(function(b){this.g=g.Ja;
this.Ld(b)},a))},y7=function(a){var b={};
b.pairingCode=a.H;b.theme=a.N;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}H5()&&(b.env_useStageMdx=1);return g.ah(b)},z7=function(a,b){s7.call(this,a,b,"ManualSession");
this.g=g.Hp((0,g.x)(this.li,this,null),150)},A7=function(a,b,c,d){g.P.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.lK,this)},B7=function(a,b){return b?g.Ya(a.l,function(c){return o5(b,c.label)},a):null},C7=function(a){W6("Controller",a)},S6=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},D7=function(a){return a.u||!!a.l.length||!!a.g},E7=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.M("yt-remote-cast2-receiver-resumed",b.i):a.M("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.Zy,a,b)),b.l?a.M("yt-remote-cast2-session-change",b.l):c&&a.g.li(null)):a.M("yt-remote-cast2-session-change",null))},F7=function(a){var b=a.i.iB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&o5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=B7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Kqa=function(a,b,c,d,e,f,k){Hqa()?Iqa(b,e,f,k)&&(H7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?I7(a,c):(window.__onGCastApiAvailable=function(l,m){l?I7(a,c):(J7("Failed to load cast API: "+m),K7(!1),H7(!1),w5("yt-remote-cast-available"),w5("yt-remote-cast-receiver"),L7(),c(!1))},d?g.Up("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?rqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?M5():(N5(),L5(Jqa.map(pqa))))):G7("Cannot initialize because not running Chrome")},L7=function(){G7("dispose");
var a=M7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);N7(!1);g.Pp(O7);O7.length=0},P7=function(){return!!g.ft("yt-remote-cast-installed")},Q7=function(){var a=g.ft("yt-remote-cast-receiver");
return a?a.friendlyName:null},R7=function(){G7("clearCurrentReceiver");
w5("yt-remote-cast-receiver")},S7=function(){return P7()?M7()?M7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},U7=function(){P7()?M7()?T7()?(G7("Requesting cast selector."),M7().requestSession()):(G7("Wait for cast API to be ready to request the session."),O7.push(g.Op("yt-remote-cast2-api-ready",U7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},V7=function(a,
b){T7()?M7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},Hqa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Nw||a},Lqa=function(a,b){M7().init(a,b)},Iqa=function(a,b,c,d){var e=!1;
M7()||(a=new A7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.et("yt-remote-cast-available",f);l5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){G7("onReceiverSelected: "+f.friendlyName);
g.et("yt-remote-cast-receiver",f);l5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){G7("onReceiverResumed: "+f.friendlyName);
g.et("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){G7("onSessionChange: "+r5(f));
f||w5("yt-remote-cast-receiver");l5("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
G7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},I7=function(a,b){K7(!0);
H7(!1);Lqa(a,function(c){c?(N7(!0),g.Rp("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),w5("yt-remote-cast-available"),w5("yt-remote-cast-receiver"),L7());b(c)})},G7=function(a){W6("cloudview",a)},J7=function(a){W6("cloudview",a)},K7=function(a){G7("setCastInstalled_ "+a);
g.et("yt-remote-cast-installed",a)},T7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},N7=function(a){G7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},H7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},W7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Je=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},X7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Je=!1;a.hasNext=!1;a.C=0;a.A=(0,g.H)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},Y7=function(a){return 1==a.playerState?((0,g.H)()-a.A)/1E3:0},Z7=function(a,b){a.C=b;
a.A=(0,g.H)()},$7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},a8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&X7(a)},b8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Je;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},e8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new k5;this.l=this.i=null;this.F=(0,g.x)(this.iI,this);this.C=(0,g.x)(this.Fk,this);this.D=(0,g.x)(this.hI,this);this.H=(0,g.x)(this.vI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.nt,this),c8(this))):c=3;0!=c&&(b?this.nt(c):g.Hp((0,g.x)(function(){this.nt(c)},this),0));
var d=S7();d&&d8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},f8=function(a){return new W7(a.o.getPlayerContextData())},c8=function(a){(0,g.A)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Sa(this.iK,b),this))},a)},g8=function(a){(0,g.A)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},h8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},j8=function(a,b,c){var d=f8(a);
Z7(d,c);-1E3!=d.playerState&&(d.playerState=b);i8(a,d)},k8=function(a,b,c){a.o.sendMessage(b,c)},i8=function(a,b){g8(a);
a.o.setPlayerContextData(b8(b));c8(a)},d8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Fk(null));
a.l=b;a.l&&(W6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Fk(a.l.media[0]))},l8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=f8(a);b.contentId!=d.videoId&&W6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;Z7(d,a.i.getEstimatedTime());i8(a,d)}else W6("CP","No cast media video. Ignoring state update.")},m8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),k8(this,b,c))},a)},n8=function(a,b,c){g.P.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Ma=this.g=null;this.O=a;this.P.push(g.Mr(window,"beforeunload",(0,g.x)(this.hD,this)));this.i=[];this.Ma=new W7;this.N=b.id;this.g=Mqa(this,c);this.g.subscribe("handlerOpened",this.mI,this);this.g.subscribe("handlerClosed",this.jI,this);this.g.subscribe("handlerError",this.kI,this);this.g.subscribe("handlerMessage",this.lI,this);wqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ma.videoId;
g.gt()&&g.et("yt-remote-session-video-id",d)},this)},o8=function(a){W6("conn",a)},Mqa=function(a,b){return new M6(Q6(a.O,"/bc"),b)},p8=function(a,b){a.M("proxyStateChange",b)},Nqa=function(a){a.u=g.Hp((0,g.x)(function(){o8("Connecting timeout");
this.Mh(1)},a),2E4)},q8=function(a){g.Jp(a.u);
a.u=NaN},r8=function(a){g.Jp(a.H);
a.H=NaN},Oqa=function(a){s8(a);
a.F=g.Hp((0,g.x)(function(){t8(this,"getNowPlaying")},a),2E4)},s8=function(a){g.Jp(a.F);
a.F=NaN},v8=function(a,b){b&&(q8(a),r8(a));
b==(O6(a.g)&&isNaN(a.u))?b&&(p8(a,1),t8(a,"getSubtitlesTrack")):b?(a.Tv()&&a.Ma.reset(),p8(a,1),t8(a,"getNowPlaying"),u8(a)):a.Mh(1)},Pqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ma.videoId&&(g.Yb(b.params)?a.Ma.g=null:a.Ma.g=b.params,a.M("remotePlayerChange"))},w8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ma.listId=b.params.listId||a.Ma.listId;a8(a.Ma,c,d);a.M("remoteQueueChange")},Qqa=function(a,b){b.params=b.params||{};
w8(a,b);x8(a,b);a.M("autoplayDismissed")},x8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
Z7(a.Ma,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ma.playerState&&(c=-1E3);a.Ma.playerState=c;c=Number(b.params.loadedTime);a.Ma.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Ma.D=isNaN(c)?0:c;c=a.Ma;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Ma;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Ma.playerState?Oqa(a):s8(a);a.M("remotePlayerChange")},Rqa=function(a,b){if(-1E3!=
a.Ma.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ma.playerState=c;c=parseInt(b.params.currentTime,10);Z7(a.Ma,isNaN(c)?0:c);a.M("remotePlayerChange")}},Sqa=function(a,b){var c="true"==b.params.muted;
a.Ma.volume=parseInt(b.params.volume,10);a.Ma.muted=c;a.M("remotePlayerChange")},Tqa=function(a,b){a.A=b.params.videoId;
a.M("nowAutoplaying",parseInt(b.params.timeout,10))},Uqa=function(a,b){var c="true"==b.params.hasNext;
a.Ma.Je="true"==b.params.hasPrevious;a.Ma.hasNext=c;a.M("previousNextChange")},u8=function(a){g.Jp(a.D);
a.D=g.Hp((0,g.x)(a.Mh,a,1),864E5)},t8=function(a,b,c){c?o8("Sending: action="+b+", params="+g.Kg(c)):o8("Sending: action="+b);
a.g.sendMessage(b,c)},y8=function(a){$6.call(this,"ScreenServiceProxy");
this.Tc=a;this.i=[];this.i.push(this.Tc.$_s("screenChange",(0,g.x)(this.cN,this)));this.i.push(this.Tc.$_s("onlineScreenChange",(0,g.x)(this.NJ,this)))},Zqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.zp("MDX_CONFIG")||b;lqa();B5();z8||(z8=new P6(b?b.loungeApiHost:void 0),H5()&&(z8.g="/api/loungedev"));A8||(A8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",A8,void 0));Vqa();var c=B8();if(!c){var d=new m7(z8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=B8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Kqa(a,d,function(m){m?C8()&&V7(C8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){l5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),D8("Initializing: "+g.Kg(b)),E8.push(g.Op("yt-remote-cast2-availability-change",function(){l5("yt-remote-receiver-availability-change")})),E8.push(g.Op("yt-remote-cast2-receiver-selected",function(){F8(null);
l5("yt-remote-auto-connect","cast-selector-receiver")})),E8.push(g.Op("yt-remote-cast2-receiver-resumed",function(){l5("yt-remote-receiver-resumed","cast-selector-receiver")})),E8.push(g.Op("yt-remote-cast2-session-change",Wqa)),E8.push(g.Op("yt-remote-connection-change",function(m){m?V7(C8(),"YouTube TV"):G8()||(V7(null,null),R7())})),a=H8(),b.isAuto&&(a.id+="#dial"),g.vq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),D8(" -- with channel params: "+
g.Kg(a)),Xqa(a),c.start(),C8()||Yqa())},$qa=function(){var a=I8();
P7()&&g.ft("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},I8=function(){var a=B8().Tc.$_gos();
var b=J8();b&&K8()&&(u5(a,b)||a.push(b));return kqa(a)},L8=function(){var a=ara();
!a&&P7()&&Q7()&&(a={key:"cast-selector-receiver",name:Q7()});return a},ara=function(){var a=I8(),b=J8();
b||(b=G8());return g.Ya(a,function(c){return b&&o5(b,c.key)?!0:!1})},J8=function(){var a=C8();
if(!a)return null;var b=B8().Id();return v5(b,a)},Wqa=function(a){D8("remote.onCastSessionChange_: "+r5(a));
if(a){var b=J8();b&&b.id==a.id?V7(b.id,"YouTube TV"):(b&&M8(),N8(a,1))}else K8()&&M8()},M8=function(){T7()?M7().stopSession():J7("stopSession called before API ready.");
var a=K8();a&&(a.disconnect(1),O8(null))},P8=function(){var a=K8();
return!!a&&3!=a.getProxyState()},D8=function(a){W6("remote",a)},B8=function(){if(!Q8){var a=g.w("yt.mdx.remote.screenService_");
Q8=a?new y8(a):null}return Q8},C8=function(){return g.w("yt.mdx.remote.currentScreenId_")},R8=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},S8=function(){return g.w("yt.mdx.remote.connectData_")},F8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},K8=function(){return g.w("yt.mdx.remote.connection_")},O8=function(a){var b=K8();
F8(null);a||R8("");g.Ia("yt.mdx.remote.connection_",a,void 0);A8&&((0,g.A)(A8,function(c){c(a)}),A8.length=0);
b&&!a?l5("yt-remote-connection-change",!1):!b&&a&&l5("yt-remote-connection-change",!0)},G8=function(){var a=g.gt();
if(!a)return null;var b=B8().Id();return v5(b,a)},N8=function(a,b){J8()&&J8();
if(T8)U8=a;else{R8(a.id);var c=new n8(z8,a,H8());c.connect(b,S8());c.subscribe("beforeDisconnect",function(d){l5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){K8()&&O8(null)});
O8(c)}},Yqa=function(){var a=G8();
a?(D8("Resume connection to: "+r5(a)),N8(a,0)):(F5(),R7(),D8("Skipping connecting because no session screen found."))},Vqa=function(){var a=H8();
if(g.Yb(a)){a=A5();var b=g.ft("yt-remote-session-name")||"",c=g.ft("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},H8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Xqa=function(a){a?(g.et("yt-remote-session-app",a.app),g.et("yt-remote-session-name",a.name)):(w5("yt-remote-session-app"),w5("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},V8=function(a,b,c){g.D.call(this);
this.u=a;this.i=b;this.l=new g.us(this);g.G(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.iJ);this.l.K(b,"captionschanged",this.gI);this.l.K(b,"captionssettingschanged",this.xA);this.l.K(b,"videoplayerreset",this.wn);this.l.K(b,"mdxautoplaycancel",this.kC);this.O=this.l.K(b,"onVolumeChange",this.Ky);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Vy,this);c.subscribe("remotePlayerChange",this.Hk,this);c.subscribe("remoteQueueChange",this.wn,this);c.subscribe("autoplayUpNext",this.zy,
this);c.subscribe("previousNextChange",this.Sy,this);c.subscribe("nowAutoplaying",this.Oy,this);c.subscribe("autoplayDismissed",this.yy,this);this.suggestion=null;this.F=new g.fC(64);this.o=new g.M(this.vA,500,this);g.G(this,this.o);this.A=new g.M(this.wA,1E3,this);g.G(this,this.A);this.I=new O5(this.IM,0,this);g.G(this,this.I);this.C={};this.P=new g.M(this.VA,1E3,this);g.G(this,this.P);this.H=new g.zl(this.FF,1E3,this);g.G(this,this.H);this.N=g.Ja;this.xA();this.wn();this.Hk()},W8=function(a,b){a.u.qd(b,
a.i.getVideoData().lengthSeconds)},Y8=function(a){W8(a,0);
a.o.stop();X8(a,new g.fC(64))},$8=function(a,b){if(Z8(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.kA(a.i.getVideoData(1).videoId,c);a.C=f8(a.g).g}},a9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ra;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Af,g5(c));X8(a,new g.fC(1))},b9=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{wQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},Z8=function(a){return f8(a.g).videoId==a.i.getVideoData(1).videoId},X8=function(a,b){a.A.stop();
var c=a.F;if(!g.lC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.TJ(a.i,d);a.F=b;c9(a.u,c,b)}},d9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",U:"\u0412\u044b \u0432\u044b\u0448\u043b\u0438 \u0438\u0437 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430"},{B:"div",G:"ytp-mdx-popup-description",U:'\u0420\u043e\u043b\u0438\u043a\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0432\u044b \u043f\u043e\u0441\u043c\u043e\u0442\u0440\u0438\u0442\u0435, \u043c\u043e\u0433\u0443\u0442 \u0431\u044b\u0442\u044c \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u044b \u0432 \u0438\u0441\u0442\u043e\u0440\u0438\u044e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430 \u043d\u0430 \u0442\u0435\u043b\u0435\u0432\u0438\u0437\u043e\u0440\u0435, \u0447\u0442\u043e \u0441\u043a\u0430\u0436\u0435\u0442\u0441\u044f \u043d\u0430 \u0440\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u044f\u0445. \u0427\u0442\u043e\u0431\u044b \u044d\u0442\u043e\u0433\u043e \u0438\u0437\u0431\u0435\u0436\u0430\u0442\u044c, \u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 "\u041e\u0442\u043c\u0435\u043d\u0430" \u0438 \u0432\u043e\u0439\u0434\u0438\u0442\u0435 \u0432 \u0430\u043a\u043a\u0430\u0443\u043d\u0442 \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435.'},
{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-cancel"],U:"\u041e\u0442\u043c\u0435\u043d\u0430"},{B:"button",V:["ytp-button","ytp-mdx-privacy-popup-confirm"],U:"\u041e\u041a"}]}]}]});this.l=new g.OP(this,250);g.G(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},f9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.dP()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.OP(this,250);g.G(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);e9(this,g.PJ(a))},e9=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.bN('\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.mC(b)||g.U(b,4)?g.bN('\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.bN('\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},g9=function(a,b){g.wT.call(this,"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},h9=function(a){g.rK.call(this,a);
this.i={key:t5(),name:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440"};this.u=null;this.o=[];this.C=this.g=null;this.A=[this.i];this.l=this.i;this.nk=new g.fC(64);this.H=0;this.Km=-1;if(!g.My(g.X(this.player))){a=this.player;var b=g.ZC(a);b&&(b=b.qk())&&(b=new g9(a,b),g.G(this,b));b=new f9(a);g.G(this,b);g.dK(a,b.element,4);this.F=new d9;g.G(this,this.F);g.dK(a,this.F.element,4);this.D=!!G8()}},c9=function(a,b,c){a.nk=c;
a.player.M("presentingplayerstatechange",new g.mD(c,b))},i9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)M8();
else{var c;if(c=g.Q(g.X(a.player).experiments,"mdx_enable_privacy_disclosure"))c=g.zp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.zp("SESSION_INDEX")||g.zp("LOGGED_IN"));c&&!a.D&&(a.player.pauseVideo(),a.F.l.show(),K8()||(T8=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,
playerParams:c.playerParams,clickTrackingParams:c.Af,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=g5(c))&&(d.locationInfo=c);c=d}else c=null;D8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(F8(c||null),T7()?M7().setLaunchParams(c||null):J7("setLaunchParams called before ready.")):!c&&P8()&&C8()==b.key?l5("yt-remote-connection-change",!0):(M8(),F8(c||null),c=B8().Id(),(c=v5(c,b.key))&&N8(c,1))}},aqa=/^https?$/i,bra=["POST",
"PUT"];g.y(e5,g.Sf);g.h=e5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.N?X4(this.N):X4(g.wY);this.P=this.N?this.N.getOptions():g.wY.getOptions();this.g.onreadystatechange=(0,g.x)(this.gw,this);try{U4(Y4(this,"Opening Xhr")),this.W=!0,this.g.open(b,String(a),!0),this.W=!1}catch(f){U4(Y4(this,"Error opening Xhr: "+f.message));b5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Ypa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Gd(),Zpa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ab(bra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{Z4(this),0<this.A&&(this.I=$pa(this.g),U4(Y4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.hw,this)):this.F=g.Gg(this.hw,this.A,this)),U4(Y4(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){U4(Y4(this,"Send error: "+f.message)),b5(this,f)}};
g.h.hw=function(){"undefined"!=typeof g.aY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,Y4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(Y4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),a5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),a5(this,!0));e5.Wa.T.call(this)};
g.h.gw=function(){this.da()||(this.W||this.C||this.o?d5(this):this.kK())};
g.h.kK=function(){d5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<c5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Fa(this.l)?this.l:String(this.l)};
var c6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},b6={"'":"\\'"},cra={};g.h=k5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Kma)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.i,a)};
g.h.yc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var iqa={AN:"atp",KP:"ska",zP:"que",ZO:"mus",JP:"sus",qO:"dsp",GP:"seq"};m5.prototype.eg=function(){var a=new m5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var G5,z5="",qqa=I5("loadCastFramework")||I5("loadCastApplicationFramework"),Jqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.y(O5,g.D);g.h=O5.prototype;g.h.dD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.H)()+this.Uc:this.za=g.Gg(this.u,this.Uc)};
g.h.stop=function(){this.za&&(g.v.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();O5.Wa.T.call(this)};
g.h.eD=function(){this.l?(this.za=g.Gg(this.u,this.l-(0,g.H)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};P5.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
P5.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=Q5.prototype;g.h.Zg=null;g.h.we=!1;g.h.Xi=null;g.h.kt=null;g.h.Ei=null;g.h.Wh=null;g.h.Vf=null;g.h.Dg=null;g.h.rh=null;g.h.sc=null;g.h.il=0;g.h.Ae=null;g.h.no=null;g.h.ng=null;g.h.Uj=-1;g.h.Xz=!0;g.h.Pg=!1;g.h.eq=0;g.h.Gn=null;var X5={},V5={};g.h=Q5.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.UL=function(a){a=a.target;var b=this.Gn;b&&3==c5(a)?b.Qj():this.eB(a)};
g.h.eB=function(a){try{if(a==this.sc)a:{var b=c5(this.sc),c=this.sc.u,d=this.sc.getStatus();if(g.Md&&!g.pd(10)||g.Od&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!f5(this.sc))break a;this.Pg||4!=b||7==c||(8==c||0>=d?this.g.se(3):this.g.se(2));g6(this);var e=this.sc.getStatus();this.Uj=e;var f=f5(this.sc);(this.we=200==e)?(4==b&&Z5(this),this.u?(a6(this,b,f),g.Ch&&this.we&&3==b&&(this.aa.ca(this.i,"tick",this.NL),this.i.start())):Y5(this,f),this.we&&!this.Pg&&(4==b?this.g.tn(this):(this.we=
!1,U5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ng=3,W5(13)):(this.ng=0,W5(14)),Z5(this),$5(this))}}catch(k){this.sc&&f5(this.sc)}finally{}};
g.h.NL=function(){var a=c5(this.sc),b=f5(this.sc);this.il<b.length&&(g6(this),a6(this,a,b),this.we&&4!=a&&U5(this))};
g.h.kL=function(a){f6((0,g.x)(this.jL,this,a),0)};
g.h.jL=function(a){this.Pg||(g6(this),Y5(this,a),U5(this))};
g.h.cz=function(a){f6((0,g.x)(this.iL,this,a),0)};
g.h.iL=function(a){this.Pg||(Z5(this),this.we=a,this.g.tn(this),this.g.se(4))};
g.h.cancel=function(){this.Pg=!0;Z5(this)};
g.h.uL=function(){this.Xi=null;var a=(0,g.H)();0<=a-this.kt?(2!=this.Wh&&this.g.se(3),Z5(this),this.ng=2,W5(18),$5(this)):e6(this,this.kt-a)};
g.h.getLastError=function(){return this.ng};g.h=k6.prototype;g.h.bq=null;g.h.Cd=null;g.h.Hn=!1;g.h.ew=null;g.h.dm=null;g.h.Oq=null;g.h.cq=null;g.h.ae=null;g.h.xf=-1;g.h.Tj=null;g.h.kj=null;g.h.connect=function(a){this.cq=a;a=l6(this.g,null,this.cq);W5(3);this.ew=(0,g.H)();var b=this.g.D;null!=b?(this.Tj=b[0],(this.kj=b[1])?(this.ae=1,m6(this)):(this.ae=2,o6(this))):(W4(a,"MODE","init"),this.Cd=new Q5(this,void 0,void 0,void 0),this.Cd.Zg=this.bq,T5(this.Cd,a,!1,null,!0),this.ae=0)};
g.h.lC=function(a){if(a)this.ae=2,o6(this);else{W5(4);var b=this.g;b.Ie=b.dg.xf;I6(b,9)}a&&this.se(2)};
g.h.zp=function(a){return this.g.zp(a)};
g.h.abort=function(){this.Cd&&(this.Cd.cancel(),this.Cd=null);this.xf=-1};
g.h.dw=function(){return!1};
g.h.Wy=function(a,b){this.xf=a.Uj;if(0==this.ae)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ie=this.xf;I6(c,2);return}this.Tj=c[0];this.kj=c[1]}else c=this.g,c.Ie=this.xf,I6(c,2);else if(2==this.ae)if(this.Hn)W5(7),this.Oq=(0,g.H)();else if("11111"==b){if(W5(6),this.Hn=!0,this.dm=(0,g.H)(),c=this.dm-this.ew,!g.Md||g.pd(10)||500>c)this.xf=200,this.Cd.cancel(),W5(12),n6(this.g,this,!0)}else W5(8),this.dm=this.Oq=(0,g.H)(),this.Hn=!1};
g.h.tn=function(){this.xf=this.Cd.Uj;if(this.Cd.we)0==this.ae?this.kj?(this.ae=1,m6(this)):(this.ae=2,o6(this)):2==this.ae&&((!g.Md||g.pd(10)?!this.Hn:200>this.Oq-this.dm)?(W5(11),n6(this.g,this,!1)):(W5(12),n6(this.g,this,!0)));else{0==this.ae?W5(9):2==this.ae&&W5(10);var a=this.g;this.Cd.getLastError();a.Ie=this.xf;I6(a,2)}};
g.h.Uk=function(){return this.g.Uk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.se=function(a){this.g.se(a)};g.h=p6.prototype;g.h.xj=null;g.h.yd=null;g.h.Rb=null;g.h.Zp=null;g.h.gm=null;g.h.yu=null;g.h.rm=null;g.h.Ck=0;g.h.zH=0;g.h.Rc=null;g.h.jg=null;g.h.lf=null;g.h.Ug=null;g.h.dg=null;g.h.ko=null;g.h.ji=-1;g.h.Kw=-1;g.h.Ie=-1;g.h.Qh=0;g.h.Ih=0;g.h.Qg=8;var J6=new g.Sf;g.y(q6,g.sf);g.y(r6,g.sf);g.y(s6,g.sf);g.h=p6.prototype;g.h.connect=function(a,b,c,d,e){W5(0);this.Zp=b;this.xj=c||{};d&&g.Ea(e)&&(this.xj.OSID=d,this.xj.OAID=e);this.A?(f6((0,g.x)(this.Qu,this,a),100),y6(this)):this.Qu(a)};
g.h.Qu=function(a){this.dg=new k6(this);this.dg.bq=null;this.dg.i=this.u;this.dg.connect(a)};
g.h.dw=function(){return 0==this.g};
g.h.bz=function(a){this.jg=null;D6(this,a)};
g.h.az=function(){this.lf=null;this.Rb=new Q5(this,this.l,"rpc",this.C);this.Rb.Zg=null;this.Rb.eq=0;var a=this.yu.clone();g.Um(a,"RID","rpc");g.Um(a,"SID",this.l);g.Um(a,"CI",this.ko?"0":"1");g.Um(a,"AID",this.ji);u6(this,a);if(!g.Md||g.pd(10))g.Um(a,"TYPE","xmlhttp"),T5(this.Rb,a,!0,this.rm,!1);else{g.Um(a,"TYPE","html");var b=this.Rb,c=!!this.rm;b.Wh=3;b.Vf=V4(a.clone());d6(b,c)}};
g.h.Wy=function(a,b){if(0!=this.g&&(this.Rb==a||this.yd==a))if(this.Ie=a.Uj,this.yd==a&&3==this.g)if(7<this.Qg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.lf){if(this.Rb)if(this.Rb.Ei+3E3<this.yd.Ei)z6(this),this.Rb.cancel(),this.Rb=null;else break a;G6(this);W5(19)}}else this.Kw=c[1],0<this.Kw-this.ji&&37500>c[2]&&this.ko&&0==this.Ih&&!this.Ug&&(this.Ug=f6((0,g.x)(this.cI,this),6E3));else I6(this,11)}else b!=cra.VN.g&&I6(this,11);else if(this.Rb==a&&
z6(this),!g.xb(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.ji=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.rm=e[2],e=e[3],null!=e?this.Qg=e:this.Qg=6,this.g=3,this.Rc&&this.Rc.Ku(),this.yu=l6(this,this.Uk()?this.rm:null,this.Zp),E6(this)):"stop"==e[0]&&I6(this,7):3==this.g&&("stop"==e[0]?I6(this,7):"noop"!=e[0]&&this.Rc&&this.Rc.Ju(e),this.Ih=0)}}};
g.h.cI=function(){null!=this.Ug&&(this.Ug=null,this.Rb.cancel(),this.Rb=null,G6(this),W5(20))};
g.h.tn=function(a){if(this.Rb==a){z6(this);this.Rb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.Ie=a.Uj;if(0!=this.g)if(a.we)1==b?(b=(0,g.H)()-a.Ei,J6.dispatchEvent(new r6(J6,a.rh?a.rh.length:0,b,this.Qh)),x6(this),this.o.length=0):E6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ie)){if(d=1==b)this.yd||this.jg||1==this.g||2<=this.Qh?d=!1:(this.jg=f6((0,g.x)(this.bz,this,a),F6(this,this.Qh)),this.Qh++,d=!0);d=!(d||2==b&&G6(this))}if(d)switch(c){case 1:I6(this,
5);break;case 4:I6(this,10);break;case 3:I6(this,6);break;case 7:I6(this,12);break;default:I6(this,2)}}};
g.h.DC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.zM=function(a){a?W5(2):(W5(1),H6(this,8))};
g.h.zp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new e5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Rc&&this.Rc.isActive(this)};
g.h.se=function(a){J6.dispatchEvent(new s6(J6,a))};
g.h.Uk=function(){return!(!g.Md||g.pd(10))};
g.h=K6.prototype;g.h.Ku=function(){};
g.h.Ju=function(){};
g.h.Iu=function(){};
g.h.lp=function(){};
g.h.Gv=function(){return{}};
g.h.isActive=function(){return!0};g.y(L6,g.D);g.h=L6.prototype;g.h.cL=function(){this.Uc=Math.min(3E5,2*this.Uc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Uc+15E3*Math.random();g.ao(this.g,a);this.i=(0,g.H)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Uc=5E3};g.y(M6,K6);g.h=M6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Hf=function(a){return this.l.ah(a)};
g.h.M=function(a,b){return this.l.M.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.qf(this.l),N6(this),g.qf(this.i),this.i=null)};
g.h.da=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new p6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Rc=null);d.Rc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ji):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):O6(this)&&A6(this.g,c)};
g.h.Ku=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)A6(this.g,a[b])}this.M("handlerOpened")};
g.h.Iu=function(a){var b=2==a&&401==this.g.Ie;4==a||b||this.i.start();this.M("handlerError",a)};
g.h.lp=function(a){if(!this.i.isActive())this.M("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Gv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.Ju=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),w6(this.g)):this.M("handlerMessage",new uqa(a[0],a[1]))};
g.h.dM=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.yd&&b++;0==b&&this.connect(this.u,this.o)};P6.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
P6.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
P6.prototype.u=function(a){a(Error("request timed out"))};var Aqa=(0,g.H)(),U6=null,Y6=Array(50),X6=-1,Z6=!1;g.y($6,g.P);$6.prototype.Id=function(){return this.g};
$6.prototype.contains=function(a){return!!u5(this.g,a)};
$6.prototype.get=function(a){return a?v5(this.g,a):null};
$6.prototype.info=function(a){W6(this.C,a)};g.t(b7,g.P);g.h=b7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.hB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Jp(this.za),this.za=NaN)};
g.h.T=function(){this.stop();g.P.prototype.T.call(this)};
g.h.hB=function(){this.za=NaN;this.g=g.Eq(Q6(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.aN,this),onError:(0,g.x)(this.ZM,this),he:(0,g.x)(this.bN,this)})};
g.h.aN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.M("pairingComplete",new n5(c))};
g.h.ZM=function(a){this.g=null;a.status&&404==a.status?this.i>=j9.length?this.M("pairingFailed",Error("DIAL polling timed out")):(a=j9[this.i],this.za=g.Hp((0,g.x)(this.hB,this),a),this.i++):this.M("pairingFailed",Error("Server error "+a.status))};
g.h.bN=function(){this.g=null;this.M("pairingFailed",Error("Server not responding"))};
var j9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.y(d7,$6);g.h=d7.prototype;g.h.start=function(){c7(this)&&this.M("screenChange");!g.ft("yt-remote-lounge-token-expiration")&&e7(this);g.Jp(this.i);this.i=g.Hp((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){c7(this);a7(this,a);f7(this,!1);this.M("screenChange");b(a);a.token||e7(this)};
g.h.remove=function(a,b){var c=c7(this);Cqa(this,a)&&(f7(this,!1),c=!0);b(a);c&&this.M("screenChange")};
g.h.eo=function(a,b,c,d){var e=c7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,f7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.M("screenChange")};
g.h.T=function(){g.Jp(this.i);d7.Wa.T.call(this)};
g.h.oD=function(a){c7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}f7(this,!b);b&&W6(this.C,"Missed "+b+" lounge tokens.")};
g.h.nD=function(a){W6(this.C,"Requesting lounge tokens failed: "+a)};g.t(h7,g.P);g.h=h7.prototype;g.h.start=function(){var a=parseInt(g.ft("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.H)()-144E5<a?0:a)?k7(this):(this.o=(0,g.H)()+3E5,g.et("yt-remote-fast-check-period",this.o),this.ls())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){g7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!v5(a,d)},this);
j7(this,b)};
g.h.T=function(){g.Jp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.P.prototype.T.call(this)};
g.h.ls=function(){g.Jp(this.l);this.l=NaN;this.i&&this.i.abort();var a=l7(this);if(h5(a)){var b=Q6(this.u,"/pairing/get_screen_availability");this.i=R6(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.GK,this,a),(0,g.x)(this.FK,this))}else j7(this,{}),k7(this)};
g.h.GK=function(a,b){this.i=null;var c=g.Sb(l7(this));if(g.sb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;j7(this,d);k7(this)}else this.Hb("Changing Screen set during request."),this.ls()};
g.h.FK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;k7(this)};
g.h.Hb=function(a){W6("OnlineScreenService",a)};g.y(m7,$6);g.h=m7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.M("screenChange"),this.i.isEmpty()||this.M("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.eo=function(a,b,c,d){this.l.contains(a)?this.l.eo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,W6(this.C,a),d(Error(a)))};
g.h.Id=function(a){return a?this.g:g.gb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.iB=function(){return(0,g.Yd)(this.Id(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.jB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new b7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(n7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.dN=function(a,b,c,d){g.Eq(Q6(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new n5(f.screen||{});if(!k.name||p7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);p7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(n7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
he:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.qf(this.l);g.qf(this.i);m7.Wa.T.call(this)};
g.h.wD=function(){q7(this);this.M("screenChange");this.i.update()};
m7.prototype.dispose=m7.prototype.dispose;g.y(s7,g.P);g.h=s7.prototype;g.h.vn=function(a){this.l=a;this.M("sessionScreen",this.l)};
g.h.Ld=function(a){this.da()||(a&&t7(this,""+a),this.l=null,this.M("sessionScreen",null))};
g.h.info=function(a){W6(this.P,a)};
g.h.lB=function(){return null};
g.h.As=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.As("");s7.Wa.T.call(this)};g.y(v7,s7);g.h=v7.prototype;g.h.zs=function(a){if(this.g){if(this.g==a)return;t7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Gqa(this)};
g.h.li=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Ld()},this),(0,g.x)(function(){this.Ld(Error("Failed to stop receiver app."))},this)):this.Ld(Error("Stopping cast device witout session."))};
g.h.As=g.Ja;g.h.T=function(){this.info("disposeInternal");g.Jp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;v7.Wa.T.call(this)};
g.h.FL=function(a,b){if(!this.da())if(b){var c=j5(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":u7(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.Wv=function(a,b,c,d){o7(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Hp((0,g.x)(this.Wv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.lB=function(){return this.g};
g.h.eN=function(a){this.da()||a||(t7(this,"Cast session died."),this.Ld())};g.y(w7,s7);g.h=w7.prototype;g.h.zs=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.li=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ja;g.Jp(this.A);this.o?this.o.stop((0,g.x)(this.Ld,this,null),(0,g.x)(this.Ld,this,"Failed to stop DIAL device.")):this.Ld()};
g.h.T=function(){this.g();this.g=g.Ja;g.Jp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;w7.Wa.T.call(this)};
g.h.hN=function(a){this.da()||a||(t7(this,"DIAL session died."),this.g(),this.g=g.Ja,this.Ld())};
g.h.rq=function(a){this.H=t5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,y7(this));a(b);x7(this)}else this.C=(0,g.x)(function(){g.Jp(this.A);this.C=g.Ja;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,y7(this));a(c);x7(this)},this),this.A=g.Hp((0,g.x)(function(){this.C()},this),100)};
g.h.SD=function(a,b,c){o7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.vn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.rq(b,c)},this),(0,g.x)(function(d){t7(this,"Failed to get DIAL screen: "+d);
this.rq(b,c)},this))};g.y(z7,s7);z7.prototype.stop=function(){this.Ld()};
z7.prototype.zs=g.Ja;z7.prototype.li=function(){g.Jp(this.g);this.g=NaN;var a=v5(this.F.Id(),this.i.label);a?this.vn(a):this.Ld(Error("No such screen"))};
z7.prototype.T=function(){g.Jp(this.g);this.g=NaN;z7.Wa.T.call(this)};g.y(A7,g.P);g.h=A7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.pK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Yy,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.DI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.da()||
(chrome.cast.addReceiverActionListener(this.o),xqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.kB,this)),this.l=F7(this),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.M("yt-remote-cast2-availability-change",D7(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.mM=function(a,b){C7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)C7("Unsetting old screen status: "+this.g.i.friendlyName),E7(this,null)}if(a&&b){if(!this.g){c=v5(this.i.Id(),a);if(!c){C7("setConnectedScreenStatus: Unknown screen.");return}var d=B7(this,c);d||(C7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ja,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
C7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);E7(this,new z7(this.i,d),!0)}this.g.As(b)}else C7("setConnectedScreenStatus: no screen.")};
g.h.nM=function(a){this.da()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.li(a):this.Hb("Setting connection data without a session")};
g.h.gN=function(){this.da()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),E7(this,null)):C7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Yy,this),(0,g.x)(this.LK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.kB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.eb(g.w("yt.mdx.remote.debug.handlers_")||[],S6);g.qf(this.g);A7.Wa.T.call(this)};
g.h.Hb=function(a){W6("Controller",a)};
g.h.Zy=function(a,b){this.g==a&&(b||E7(this,null),this.M("yt-remote-cast2-session-change",b))};
g.h.lK=function(a,b){if(!this.da())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),C7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)C7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{C7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.M("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:E7(this,
new z7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:E7(this,new w7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:E7(this,new v7(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.DI=function(a){if(this.da())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return C7("Reselecting dial screen."),
this.M("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);E7(this,new w7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.SD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.rq,b))};
g.h.Yy=function(a){if(!this.da()){C7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)C7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),E7(this,new v7(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=v5(this.i.Id(),c.label);d&&o5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(C7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new v7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.Zy,this,this.g)),this.g.li(null));this.g.zs(a)}}};
g.h.fN=function(){return this.g?this.g.lB():null};
g.h.LK=function(a){this.da()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&E7(this,null))};
g.h.pK=function(a){C7("Receiver availability updated: "+a);if(!this.da()){var b=D7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;D7(this)!=b&&this.M("yt-remote-cast2-availability-change",D7(this))}};
g.h.kB=function(){this.da()||(this.l=F7(this),C7("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.M("yt-remote-cast2-availability-change",D7(this)))};
A7.prototype.setLaunchParams=A7.prototype.nM;A7.prototype.setConnectedScreenStatus=A7.prototype.mM;A7.prototype.stopSession=A7.prototype.gN;A7.prototype.getCastSession=A7.prototype.fN;A7.prototype.requestSession=A7.prototype.requestSession;A7.prototype.init=A7.prototype.init;A7.prototype.dispose=A7.prototype.dispose;var O7=[];W7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";X7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Je=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
W7.prototype.isAdPlaying=function(){return 1081==this.playerState};
W7.prototype.getDuration=function(){return this.u?this.D+Y7(this):this.D};
W7.prototype.clone=function(){return new W7(b8(this))};g.t(e8,g.P);g.h=e8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ja,m8(this,"play")):k8(this,"play"),j8(this,1,$7(f8(this))),this.M("remotePlayerChange")):h8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ja,m8(this,"pause")):k8(this,"pause"),j8(this,2,$7(f8(this))),this.M("remotePlayerChange")):h8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=f8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,m8(this,"seekTo",{newTime:a}))}else k8(this,"seekTo",{newTime:a});j8(this,3,a);this.M("remotePlayerChange")}else h8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ja,m8(this,"stopVideo")):k8(this,"stopVideo");var a=f8(this);a.index=-1;a.videoId="";X7(a);i8(this,a);this.M("remotePlayerChange")}else h8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=f8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){W6("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){W6("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);k8(this,"setVolume",e)}c.muted=b;c.volume=a;i8(this,c)}else h8(this,g.Sa(this.setVolume,a,b))};
g.h.kA=function(a,b){if(1==this.g){var c=f8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.fc(d,c.g));k8(this,"setSubtitlesTrack",d);i8(this,c)}else h8(this,g.Sa(this.kA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();k8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=f8(this);d.audioTrackId=c;i8(this,d)}else h8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=f8(this);c=c||0;var m={videoId:a,currentIndex:c};a8(l,a,c);g.Ea(b)&&(Z7(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));k8(this,"setPlaylist",m);d||i8(this,l)};
g.h.Cn=function(a,b){if(1==this.g){if(a&&b){var c=f8(this);a8(c,a,b);i8(this,c)}k8(this,"previous")}else h8(this,g.Sa(this.Cn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=f8(this);a8(c,a,b);i8(this,c)}k8(this,"next")}else h8(this,g.Sa(this.nextVideo,a,b))};
g.h.hv=function(){1==this.g?k8(this,"dismissAutoplay"):h8(this,this.hv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.M("proxyStateChange",a,this.g)}g.P.prototype.dispose.call(this)};
g.h.T=function(){g8(this);this.o=null;this.u.clear();d8(this,null);g.P.prototype.T.call(this)};
g.h.nt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.M("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.iK=function(a,b){this.M(a,b)};
g.h.iI=function(a){if(!a)this.Fk(null),d8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=f8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)W6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,i8(this,b)}};
g.h.Fk=function(a){W6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),l8(this),this.M("remotePlayerChange")};
g.h.hI=function(a){a?(l8(this),this.M("remotePlayerChange")):this.Fk(null)};
g.h.Ss=function(){k8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.vI=function(){var a=S7();a&&d8(this,a)};
g.h.Hb=function(a){W6("CP",a)};g.t(n8,g.P);g.h=n8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Ma.listId=c);this.Ma.videoId=d;this.Ma.index=k||0;this.Ma.state=3;Z7(this.Ma,m);this.o="UNSUPPORTED";o8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,C5())}else o8("Connecting without params"),this.g.connect({},a,C5());Nqa(this)};
g.h.dispose=function(){this.da()||(this.M("beforeDispose"),p8(this,3));g.P.prototype.dispose.call(this)};
g.h.T=function(){q8(this);s8(this);r8(this);g.Jp(this.C);this.C=NaN;g.Jp(this.D);this.D=NaN;this.l=null;g.Nr(this.P);this.P.length=0;this.g.dispose();g.P.prototype.T.call(this);this.o=this.A=this.i=this.Ma=this.g=null};
g.h.hD=function(){this.Mh(2)};
g.h.mI=function(){o8("Channel opened");this.I&&(this.I=!1,r8(this),this.H=g.Hp((0,g.x)(function(){o8("Timing out waiting for a screen.");this.Mh(1)},this),15E3));
oqa(vqa(this.g),this.N)};
g.h.jI=function(){o8("Channel closed");isNaN(this.u)?F5(!0):F5();this.dispose()};
g.h.kI=function(a){F5();isNaN(this.Ij())?(o8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,o8("Channel error: "+a+" with reconnection in "+this.Ij()+" ms"),p8(this,2))};
g.h.lI=function(a){a.params?o8("Received: action="+a.action+", params="+g.Kg(a.params)):o8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=j5(a.params.devices);this.i=(0,g.B)(a,function(c){return new m5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
v8(this,a);break;case "loungeScreenDisconnected":g.fb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
v8(this,!1);break;case "remoteConnected":var b=new m5(j5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||dqa(this.i,b);
break;case "remoteDisconnected":b=new m5(j5(a.params.device));g.fb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":w8(this,a);break;case "nowPlaying":Qqa(this,a);break;case "onStateChange":x8(this,a);break;case "onAdStateChange":Rqa(this,a);break;case "onVolumeChanged":Sqa(this,a);break;case "onSubtitlesTrackChanged":Pqa(this,a);break;case "nowAutoplaying":Tqa(this,a);break;case "autoplayDismissed":this.M("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.M("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.M("autoplayModeChange",this.o);"DISABLED"==this.o&&this.M("autoplayDismissed");break;case "onHasPreviousNextChanged":Uqa(this,a);break;case "requestAssistedSignIn":this.M("assistedSignInRequested",a.params.authCode);break;default:o8("Unrecognized action: "+a.action)}};
g.h.aM=function(){if(this.l){var a=this.l;this.l=null;this.Ma.videoId!=a&&t8(this,"getNowPlaying")}};
g.h.XC=function(){var a=3;this.da()||(a=0,isNaN(this.Ij())?O6(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Mh=function(a){o8("Disconnecting with "+a);q8(this);this.M("beforeDisconnect",a);1==a&&F5();N6(this.g,a);this.dispose()};
g.h.WC=function(){var a=this.Ma;this.l&&(a=this.Ma.clone(),a8(a,this.l,a.index));return b8(a)};
g.h.oM=function(a){var b=new W7(a);b.videoId&&b.videoId!=this.Ma.videoId&&(this.l=b.videoId,g.Jp(this.C),this.C=g.Hp((0,g.x)(this.aM,this),5E3));var c=[];this.Ma.listId==b.listId&&this.Ma.videoId==b.videoId&&this.Ma.index==b.index||c.push("remoteQueueChange");this.Ma.playerState==b.playerState&&this.Ma.volume==b.volume&&this.Ma.muted==b.muted&&$7(this.Ma)==$7(b)&&g.Kg(this.Ma.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Ma.reset(a);(0,g.A)(c,function(d){this.M(d)},this)};
g.h.Tv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Ij=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.H)():NaN};
g.h.PC=function(){return this.o||"UNSUPPORTED"};
g.h.QC=function(){return this.A||""};
g.h.YM=function(){if(!isNaN(this.Ij())){var a=this.g.i;g.bo(a.g);a.start()}};
g.h.hM=function(a,b){t8(this,a,b);u8(this)};
n8.prototype.subscribe=n8.prototype.subscribe;n8.prototype.unsubscribeByKey=n8.prototype.Hf;n8.prototype.getProxyState=n8.prototype.XC;n8.prototype.disconnect=n8.prototype.Mh;n8.prototype.getPlayerContextData=n8.prototype.WC;n8.prototype.setPlayerContextData=n8.prototype.oM;n8.prototype.getOtherConnectedRemoteId=n8.prototype.Tv;n8.prototype.getReconnectTimeout=n8.prototype.Ij;n8.prototype.getAutoplayMode=n8.prototype.PC;n8.prototype.getAutoplayVideoId=n8.prototype.QC;n8.prototype.reconnect=n8.prototype.YM;
n8.prototype.sendMessage=n8.prototype.hM;g.t(y8,$6);g.h=y8.prototype;g.h.Id=function(a){return this.Tc.$_gs(a)};
g.h.contains=function(a){return!!this.Tc.$_c(a)};
g.h.get=function(a){return this.Tc.$_g(a)};
g.h.start=function(){this.Tc.$_st()};
g.h.add=function(a,b,c){this.Tc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Tc.$_r(a,b,c)};
g.h.eo=function(a,b,c,d){this.Tc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Tc.$_ubk(this.i[a]);this.i.length=0;this.Tc=null;$6.prototype.T.call(this)};
g.h.cN=function(){this.M("screenChange")};
g.h.NJ=function(){this.M("onlineScreenChange")};
m7.prototype.$_st=m7.prototype.start;m7.prototype.$_gspc=m7.prototype.dN;m7.prototype.$_gsppc=m7.prototype.jB;m7.prototype.$_c=m7.prototype.contains;m7.prototype.$_g=m7.prototype.get;m7.prototype.$_a=m7.prototype.add;m7.prototype.$_un=m7.prototype.eo;m7.prototype.$_r=m7.prototype.remove;m7.prototype.$_gs=m7.prototype.Id;m7.prototype.$_gos=m7.prototype.iB;m7.prototype.$_s=m7.prototype.subscribe;m7.prototype.$_ubk=m7.prototype.Hf;var U8=null,T8=!1,z8=null,A8=null,Q8=null,E8=[];g.t(V8,g.D);g.h=V8.prototype;
g.h.T=function(){g.D.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.N();this.g.unsubscribe("proxyStateChange",this.Vy,this);this.g.unsubscribe("remotePlayerChange",this.Hk,this);this.g.unsubscribe("remoteQueueChange",this.wn,this);this.g.unsubscribe("autoplayUpNext",this.zy,this);this.g.unsubscribe("previousNextChange",this.Sy,this);this.g.unsubscribe("nowAutoplaying",this.Oy,this);this.g.unsubscribe("autoplayDismissed",this.yy,this);this.g=this.u=null};
g.h.wx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(Z8(this)){if(!f8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==f8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Qj(c[0],c[1]);break;case "control_subtitles_set_track":$8(this,c[0]);break;case "control_set_audio_track":c=c[0],Z8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();a9(this,0==c?void 0:c);break;case "control_seek":a9(this,c[0]);break;case "control_subtitles_set_track":$8(this,c[0]);break;case "control_set_audio_track":c=c[0],Z8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.gI=function(a){this.I.dD(a)};
g.h.IM=function(a){this.wx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.xA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||$8(this,a)};
g.h.Ky=function(a){if(Z8(this)){this.g.unsubscribe("remotePlayerChange",this.Hk,this);var b=Math.round(a.volume);a=!!a.muted;var c=f8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Hk,this)}};
g.h.iJ=function(){g.Yb(this.C)||b9(this,this.C);this.D=!1};
g.h.Vy=function(a,b){this.A.stop();2==b&&this.wA()};
g.h.Hk=function(){if(Z8(this)){this.o.stop();var a=f8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Km=1;break;case 1082:case 1083:this.u.Km=0;break;default:this.u.Km=-1}switch(a.playerState){case 1081:case 1:X8(this,new g.fC(8));this.vA();break;case 1085:case 3:X8(this,new g.fC(9));break;case 1083:case 0:X8(this,new g.fC(2));this.H.stop();W8(this,this.i.getVideoData().lengthSeconds);break;case 1084:X8(this,new g.fC(4));break;case 2:X8(this,new g.fC(4));W8(this,$7(a));
break;case -1:X8(this,new g.fC(64));break;case -1E3:X8(this,new g.fC(128,{errorCode:"mdx.remoteerror",message:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f."}))}a=f8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&
a.kind==b.kind:1)||(this.C=a,b9(this,a));a=f8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.VA()}else Y8(this)};
g.h.Sy=function(){this.i.M("mdxpreviousnextchange")};
g.h.wn=function(){Z8(this)||Y8(this)};
g.h.kC=function(){this.g.hv()};
g.h.zy=function(a){a&&(a=g.Eq("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.nL,this)}))&&(this.N=(0,g.x)(a.abort,a))};
g.h.nL=function(a,b){var c=new g.TA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.M("mdxautoplayupnext",c)};
g.h.Oy=function(a){isNaN(a)||this.i.M("mdxnowautoplaying",a)};
g.h.yy=function(){this.i.M("mdxautoplaycanceled")};
g.h.FF=function(a,b){-1==f8(this.g).playerState?a9(this,a):b&&this.g.seekTo(a)};
g.h.VA=function(){if(Z8(this)){var a=f8(this.g);this.l.La(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Ky)}};
g.h.vA=function(){this.o.stop();if(!this.g.da()){var a=f8(this.g);1==a.playerState&&X8(this,new g.fC(8));W8(this,$7(a));this.o.start()}};
g.h.wA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(d9,g.W);d9.prototype.o=function(){l5("mdx-privacy-popup-cancel");this.l.hide()};
d9.prototype.A=function(){l5("mdx-privacy-popup-confirm");this.l.hide()};g.t(f9,g.W);f9.prototype.u=function(a){e9(this,a.state)};g.t(g9,g.wT);g9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.xT(this,(0,g.B)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.re(this.A(a)),this.enable(!0)):this.enable(!1)};
g9.prototype.A=function(a){return a.key};
g9.prototype.qe=function(a){return"cast-selector-receiver"==a?"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c":this.F[a].name};
g9.prototype.Ic=function(a){g.wT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(h9,g.rK);g.h=h9.prototype;
g.h.create=function(){Zqa(g.Dy(g.X(this.player)));this.o.push(g.Op("yt-remote-before-disconnect",this.dI,this));this.o.push(g.Op("yt-remote-connection-change",this.qK,this));this.o.push(g.Op("yt-remote-receiver-availability-change",this.Ty,this));this.o.push(g.Op("yt-remote-auto-connect",this.oK,this));this.o.push(g.Op("yt-remote-receiver-resumed",this.nK,this));this.o.push(g.Op("mdx-privacy-popup-confirm",this.QL,this));this.o.push(g.Op("mdx-privacy-popup-cancel",this.PL,this));this.Ty()};
g.h.load=function(){this.player.cancelPlayback();g.rK.prototype.load.call(this);this.u=new V8(this,this.player,this.g);var a=(a=S8())?a.currentTime:0;var b=P8()?new e8(K8(),void 0):null;0==a&&b&&(a=$7(f8(b)));0!=a&&this.qd(a);c9(this,this.nk,this.nk);g.wX(this.player.app,6)};
g.h.unload=function(){this.player.M("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.rK.prototype.unload.call(this);g.wX(this.player.app,5)};
g.h.T=function(){g.Pp(this.o);g.rK.prototype.T.call(this)};
g.h.Ve=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.wx.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.Km};
g.h.ZC=function(){return this.loaded?this.u.suggestion:null};
g.h.Je=function(){return this.g?f8(this.g).Je:!1};
g.h.hasNext=function(){return this.g?f8(this.g).hasNext:!1};
g.h.qd=function(a,b){this.H=a||0;this.player.M("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=f8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ac():!a.isAdPlaying()&&this.player.ac(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+Y7(a):a.l,isAtLiveHead:1>=(a.u?a.i+Y7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+Y7(a):a.i,seekableStart:0<a.o?a.o+
Y7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Cn=function(){this.g&&this.g.Cn()};
g.h.dI=function(a){1==a&&(this.C=this.g?f8(this.g):null)};
g.h.qK=function(){var a=P8()?new e8(K8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,$7(a)));this.player.M("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Ty=function(){this.A=[this.i].concat($qa());var a=L8()||this.i;i9(this,a);this.player.la("onMdxReceiversChange")};
g.h.oK=function(){var a=L8();i9(this,a)};
g.h.nK=function(){this.l=L8()};
g.h.QL=function(){this.D=!0;T8=!1;U8&&N8(U8,1);U8=null};
g.h.PL=function(){this.D=!1;i9(this,this.i);this.l=this.i;T8=!1;U8=null;this.player.playVideo()};
g.h.wc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?U7():i9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&U7(),!0):!1}};
g.h.Ss=function(){this.g.Ss()};
g.h.Kb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.NU.remote=h9;})(_yt_player);
